// Generated by npm run prepare:supabase. Edit the original Joy payroll source instead.
import { and, asc, desc, eq, gte, inArray, lt } from "drizzle-orm";
import type { AuthenticatedUser } from "../supabase-runtime.ts";
import { getDb, getRawDb } from "../supabase-runtime.ts";
import {
  accommodationCharges,
  appUsers,
  attendanceEntries,
  auditEvents,
  clientUnits,
  employees,
  payrollItems,
  payrollRemarks,
  payrollRules,
  payrollRuns,
  shiftDefinitions,
  vendors,
} from "./schema.ts";
import {
  ATTENDANCE_CODES,
  accommodationTotal,
  attendanceSummary,
  deductionFields,
  defaultPayrollRules,
  earningFields,
  numberValue,
  payrollTotals,
  roundMoney,
  salaryForAttendance,
  validationForEmployee,
} from "./payroll-calculations.ts";
import {
  ACCESS_MODULES,
  DEFAULT_PERMISSIONS,
  canManage,
  canView,
  normalizePermissions,
  normalizeRole,
  type AccessModule,
} from "./access-control.ts";

type Db = ReturnType<typeof getDb>;
type EmployeeRow = typeof employees.$inferSelect;
type PayrollRunRow = typeof payrollRuns.$inferSelect;
type PayrollItemRow = typeof payrollItems.$inferSelect;
type AppUserRow = typeof appUsers.$inferSelect;
type Payload = Record<string, unknown> & { action?: string; runId?: string };

type AppAccess = {
  identity: AuthenticatedUser;
  profile: ReturnType<typeof appUserProfile>;
};

class RequestError extends Error {
  constructor(message: string, public status = 400) { super(message); }
}

function errorMessages(error: unknown) {
  const messages: string[] = [];
  let current = error;
  while (current instanceof Error && messages.length < 4) {
    messages.push(current.message);
    current = "cause" in current ? current.cause : null;
  }
  return messages;
}

const RUN_ID = "RUN-AUG26-JMS-WAT1";

function isAutomatedSiteIdentity(email: string) {
  return /^sites-[a-z0-9-]+-noreply@chatgpt\.com$/i.test(email);
}

function parsePermissionJson(value: string) {
  try { return JSON.parse(value) as unknown; } catch { return {}; }
}

function appUserProfile(row: AppUserRow) {
  const role = normalizeRole(row.role);
  const permissions = normalizePermissions(role, parsePermissionJson(row.permissionsJson));
  return {
    id: row.id,
    email: row.email,
    fullName: row.fullName,
    role,
    status: row.status,
    permissions,
    canApprovePayroll: role === "super_admin" || Boolean(row.canApprovePayroll),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    lastLoginAt: row.lastLoginAt,
  };
}

async function requireAppAccess(db: Db, identity: AuthenticatedUser | null): Promise<AppAccess> {
  if (!identity) throw new RequestError("Secure sign-in is required to access Joy Payroll Manager", 401);
  const email = identity.email.trim().toLowerCase();
  if (isAutomatedSiteIdentity(email)) throw new RequestError("Automated Site services cannot access confidential payroll records.", 403);
  let [row] = await db.select().from(appUsers).where(eq(appUsers.email, email)).limit(1);
  if (!row) {
    const existingProfiles = await db.select().from(appUsers);
    const existingHuman = existingProfiles.find((profile) => !isAutomatedSiteIdentity(profile.email));
    if (!existingHuman) {
      const now = new Date().toISOString();
      const values = {
        email,
        fullName: identity.fullName,
        role: "super_admin",
        status: "active",
        permissionsJson: JSON.stringify(DEFAULT_PERMISSIONS.super_admin),
        canApprovePayroll: 1,
        createdBy: email,
        createdAt: now,
        updatedAt: now,
        lastLoginAt: now,
      };
      const automatedProfile = existingProfiles.find((profile) => isAutomatedSiteIdentity(profile.email));
      if (automatedProfile) {
        await db.update(appUsers).set(values).where(eq(appUsers.id, automatedProfile.id));
      } else {
        await db.insert(appUsers).values({ id: `USER-${crypto.randomUUID()}`, ...values }).onConflictDoNothing();
      }
      [row] = await db.select().from(appUsers).where(eq(appUsers.email, email)).limit(1);
    }
  }
  if (!row) throw new RequestError("Your payroll access profile has not been created. Contact the Super Admin.", 403);
  if (row.status !== "active") throw new RequestError("Your payroll access profile is inactive. Contact the Super Admin.", 403);
  const lastLoginAt = new Date().toISOString();
  await db.update(appUsers).set({ fullName: identity.fullName ?? row.fullName, lastLoginAt }).where(eq(appUsers.id, row.id));
  return { identity, profile: appUserProfile({ ...row, fullName: identity.fullName ?? row.fullName, lastLoginAt }) };
}

function requireModule(access: AppAccess, module: AccessModule, level: "view" | "manage") {
  const allowed = level === "manage" ? canManage(access.profile.permissions, module) : canView(access.profile.permissions, module);
  if (!allowed) throw new RequestError(`Your ${access.profile.role.replaceAll("_", " ")} profile does not have ${level} access to ${ACCESS_MODULES.find((item) => item.id === module)?.label ?? module}.`, 403);
}

function requireSuperAdmin(access: AppAccess) {
  if (access.profile.role !== "super_admin") throw new RequestError("Only a Super Admin can manage users and access profiles.", 403);
}

function actionPermission(action: string, payload: Payload): { module: AccessModule; level: "manage" } | null {
  if (action === "save-app-user" || ((action === "set-record-status" || action === "delete-record") && payload.entityType === "app_user")) return { module: "users", level: "manage" };
  if (["create-vendor", "save-client", "create-unit", "save-unit"].includes(action) || ((action === "set-record-status" || action === "delete-record") && ["client", "unit"].includes(String(payload.entityType)))) return { module: "clients", level: "manage" };
  if (action === "save-employee" || ((action === "set-record-status" || action === "delete-record") && payload.entityType === "employee")) return { module: "employees", level: "manage" };
  if (["save-shift", "save-remark"].includes(action) || ((action === "set-record-status" || action === "delete-record") && ["shift", "remark"].includes(String(payload.entityType)))) return { module: "masters", level: "manage" };
  if (["save-attendance", "delete-attendance"].includes(action)) return { module: "attendance", level: "manage" };
  if (["save-accommodation", "delete-accommodation"].includes(action)) return { module: "accommodation", level: "manage" };
  if (action === "save-rules") return { module: "settings", level: "manage" };
  if (action === "import-workbook") return { module: payload.sourceType === "salary" ? "payroll" : payload.sourceType === "csv" ? "employees" : "attendance", level: "manage" };
  if (["create-run", "save-payroll-item", "resolve-issues", "recalculate", "reopen", "reset-demo", "delete-payroll-run"].includes(action)) return { module: "payroll", level: "manage" };
  return null;
}

async function createDefaultShifts(db: Db, vendorId: string) {
  await db.insert(shiftDefinitions).values([
    { id: `SHIFT-${crypto.randomUUID()}`, vendorId, name: "General", startTime: "09:00", endTime: "18:00" },
    { id: `SHIFT-${crypto.randomUUID()}`, vendorId, name: "1st Shift", startTime: "06:00", endTime: "14:00" },
    { id: `SHIFT-${crypto.randomUUID()}`, vendorId, name: "2nd Shift", startTime: "14:00", endTime: "22:00" },
    { id: `SHIFT-${crypto.randomUUID()}`, vendorId, name: "3rd Shift", startTime: "22:00", endTime: "06:00" },
  ]);
}

async function ensureDemoData() {
  const db = getDb();
  const existingVendors = await db.select({ id: vendors.id }).from(vendors);
  const [existingRun] = await db.select({ id: payrollRuns.id }).from(payrollRuns).where(eq(payrollRuns.id, RUN_ID)).limit(1);
  const [existingActivity] = await db.select({ id: auditEvents.id }).from(auditEvents).limit(1);
  if (existingRun || existingVendors.length || existingActivity) return;

  const vendorRows = [
    {
      id: "vendor-jms",
      code: "JMS",
      name: "Joy Manpower Service",
      legalName: "Joy Manpower Service",
      epfCode: "CBCBE1724259000",
      esiCode: "56001195190001001",
      gstin: "33AOAPR4773D1Z2",
    },
    {
      id: "vendor-jcs",
      code: "JCS",
      name: "Joy Corporate Solutions",
      legalName: "Joy Corporate Solutions Private Limited",
      epfCode: "CBCBE3415419000",
      esiCode: "56001461400000999",
      gstin: "33AAGCJ6200N1ZL",
    },
  ];
  if (!existingVendors.length) {
    await db.insert(vendors).values(vendorRows);
    for (const vendor of vendorRows) await createDefaultShifts(db, vendor.id);
  }

  const unitRows = [
    { id: "unit-watertec-1", vendorId: "vendor-jms", clientName: "Watertec India", unitName: "Unit I", location: "Coimbatore", employeeCount: 126 },
    { id: "unit-bull-1", vendorId: "vendor-jms", clientName: "Bull Machines", unitName: "Unit I", location: "Coimbatore", employeeCount: 98 },
    { id: "unit-propel-1", vendorId: "vendor-jcs", clientName: "Propel Industries", unitName: "Unit I", location: "Coimbatore", employeeCount: 74 },
    { id: "unit-velan-1", vendorId: "vendor-jcs", clientName: "Velan Valves", unitName: "Unit I", location: "Coimbatore", employeeCount: 62 },
  ];
  const currentUnits = await db.select({ id: clientUnits.id }).from(clientUnits);
  const unitIds = new Set(currentUnits.map((unit) => unit.id));
  const missingUnits = unitRows.filter((unit) => !unitIds.has(unit.id));
  if (missingUnits.length) await db.insert(clientUnits).values(missingUnits);

  const employeeRows = [
    { id: "emp-1001", vendorId: "vendor-jms", clientUnitId: "unit-watertec-1", employeeCode: "J1001", name: "Arun Kumar", department: "Production", dateOfJoining: "2024-02-12", uanMasked: "XXXXXXXX1204", esiMasked: "XXXXXX4102", bankAccountMasked: "XXXXXX4821", ifscMasked: "CUB000****", bankName: "City Union Bank", accommodationType: "Joy Room", roomNumber: "AR1", paymentMode: "bank", salaryAmount: 14560, complianceStatus: "ready" },
    { id: "emp-1002", vendorId: "vendor-jms", clientUnitId: "unit-watertec-1", employeeCode: "J1002", name: "Meena Devi", department: "Packing", dateOfJoining: "2024-06-03", uanMasked: "XXXXXXXX2718", esiMasked: "XXXXXX6670", bankAccountMasked: "XXXXXX7135", ifscMasked: "HDFC00****", bankName: "HDFC Bank", accommodationType: "Outside Room", roomNumber: "OR2", paymentMode: "bank", salaryAmount: 13720, complianceStatus: "ready" },
    { id: "emp-1003", vendorId: "vendor-jms", clientUnitId: "unit-watertec-1", employeeCode: "J1003", name: "Karthik S", department: "Quality", dateOfJoining: "2025-01-20", uanMasked: null, esiMasked: "XXXXXX1038", bankAccountMasked: null, ifscMasked: null, bankName: null, accommodationType: "Tamil Own", roomNumber: "Tamil", paymentMode: "cash", salaryAmount: 12992, complianceStatus: "review" },
    { id: "emp-1004", vendorId: "vendor-jms", clientUnitId: "unit-watertec-1", employeeCode: "J1004", name: "Priya M", department: "Assembly", dateOfJoining: "2023-11-09", uanMasked: "XXXXXXXX9952", esiMasked: "XXXXXX7814", bankAccountMasked: "XXXXXX2284", ifscMasked: "IOBA00****", bankName: "Indian Overseas Bank", accommodationType: "Joy Room", roomNumber: "AR1", paymentMode: "bank", salaryAmount: 15400, complianceStatus: "ready" },
    { id: "emp-1005", vendorId: "vendor-jms", clientUnitId: "unit-watertec-1", employeeCode: "J1005", name: "Naveen R", department: "Machine Shop", dateOfJoining: "2024-08-18", uanMasked: "XXXXXXXX6307", esiMasked: "XXXXXX8421", bankAccountMasked: "XXXXXX3098", ifscMasked: "SBIN00****", bankName: "State Bank of India", accommodationType: "Tamil Own", roomNumber: "Tamil", paymentMode: "bank", salaryAmount: 16688, complianceStatus: "ready" },
    { id: "emp-1006", vendorId: "vendor-jms", clientUnitId: "unit-watertec-1", employeeCode: "J1006", name: "Divya K", department: "Stores", dateOfJoining: "2025-03-11", uanMasked: "XXXXXXXX3149", esiMasked: null, bankAccountMasked: "XXXXXX8091", ifscMasked: null, bankName: "Canara Bank", accommodationType: "Outside Room", roomNumber: "OR2", paymentMode: "cash", salaryAmount: 12208, complianceStatus: "review" },
  ];
  const currentEmployees = await db.select({ id: employees.id }).from(employees).where(eq(employees.clientUnitId, "unit-watertec-1"));
  const employeeIds = new Set(currentEmployees.map((employee) => employee.id));
  const missingEmployees = employeeRows.filter((employee) => !employeeIds.has(employee.id));
  for (let index = 0; index < missingEmployees.length; index += 4) {
    await db.insert(employees).values(missingEmployees.slice(index, index + 4));
  }

  const attendancePattern = [
    ["P", "P", "P", "WO", "P", "P", "P"],
    ["P", "P", "L", "P", "P", "WO", "P"],
    ["P", "A", "A", "P", "P", "P", "WO"],
    ["P", "P", "HP", "WO", "P", "P", "P"],
    ["P", "P", "P", "P", "WO", "P", "P"],
    ["P", "L", "P", "P", "P", "WO", "A"],
  ];
  const shifts = ["General", "1st Shift", "2nd Shift", "General", "3rd Shift", "1st Shift"];
  const attendanceRows = employeeRows.flatMap((employee, employeeIndex) =>
    attendancePattern[employeeIndex].map((statusCode, dayIndex) => ({
      employeeId: employee.id,
      attendanceDate: `2026-08-${String(dayIndex + 1).padStart(2, "0")}`,
      statusCode,
      shiftCode: dayIndex === 4 ? "2nd Shift" : shifts[employeeIndex],
      overtimeHours: statusCode === "HP" ? 8 : dayIndex === 5 && statusCode === "P" ? 2 : 0,
      source: "demo",
    })),
  );
  const currentAttendance = await db.select().from(attendanceEntries).where(and(gte(attendanceEntries.attendanceDate, "2026-08-01"), lt(attendanceEntries.attendanceDate, "2026-09-01")));
  const attendanceIds = new Set(currentAttendance.map((entry) => `${entry.employeeId}:${entry.attendanceDate}`));
  const missingAttendance = attendanceRows.filter((entry) => !attendanceIds.has(`${entry.employeeId}:${entry.attendanceDate}`));
  for (let index = 0; index < missingAttendance.length; index += 10) {
    await db.insert(attendanceEntries).values(missingAttendance.slice(index, index + 10));
  }

  await db.insert(payrollRuns).values({
    id: RUN_ID,
    vendorId: "vendor-jms",
    clientUnitId: "unit-watertec-1",
    payPeriod: "2026-08",
    status: "needs_review",
    employeeCount: 6,
    grossEarnings: 152800,
    statutoryDeductions: 16330,
    otherDeductions: 4450,
    accommodationDeductions: 7400,
    netPayable: 124870,
    bankPayable: 87130,
    cashPayable: 37740,
    issueCount: 2,
  });

  const demoItems = [
    payrollItem("item-1001", "emp-1001", 26, 1, 1, 4, 1, 28, 12, 26000, 2960, 600, 2200, 0, 20240, "ready", null),
    payrollItem("item-1002", "emp-1002", 25, 1, 2, 4, 0, 27, 8, 24500, 2790, 450, 1500, 0, 19760, "ready", null),
    payrollItem("item-1003", "emp-1003", 24, 3, 1, 3, 0, 25, 6, 23200, 1580, 800, 0, 0, 20820, "review", "UAN and bank details pending"),
    payrollItem("item-1004", "emp-1004", 27, 0, 0, 4, 1, 29, 18, 27500, 3130, 1200, 2200, 0, 20970, "ready", null),
    payrollItem("item-1005", "emp-1005", 26, 1, 1, 4, 0, 27, 10, 29800, 3390, 500, 0, 250, 26160, "ready", null),
    payrollItem("item-1006", "emp-1006", 23, 2, 2, 4, 0, 25, 4, 21800, 2480, 900, 1500, 0, 16920, "review", "ESI number and IFSC pending"),
  ];
  for (let index = 0; index < demoItems.length; index += 2) {
    await db.insert(payrollItems).values(demoItems.slice(index, index + 2));
  }

  await db.insert(accommodationCharges).values([
    { runId: RUN_ID, employeeId: "emp-1001", roomNumber: "AR1", rent: 1200, food: 700, rationShare: 300 },
    { runId: RUN_ID, employeeId: "emp-1002", roomNumber: "OR2", rent: 1000, bus: 300, rationShare: 200 },
    { runId: RUN_ID, employeeId: "emp-1004", roomNumber: "AR1", rent: 1200, advance: 500, rationShare: 300, oldPending: 200 },
    { runId: RUN_ID, employeeId: "emp-1006", roomNumber: "OR2", rent: 1000, bus: 300, food: 200 },
  ]);
}

function payrollItem(
  id: string,
  employeeId: string,
  presentDays: number,
  absentDays: number,
  leaveDays: number,
  weekOffDays: number,
  holidayPresentDays: number,
  payableDays: number,
  overtimeHours: number,
  grossEarnings: number,
  statutoryDeductions: number,
  otherDeductions: number,
  accommodationDeduction: number,
  returnAmount: number,
  netPayable: number,
  validationStatus: string,
  validationMessage: string | null,
) {
  const basic = Math.round(grossEarnings * 0.56);
  const hra = Math.round(grossEarnings * 0.18);
  const overtimeWages = Math.round(overtimeHours * 96);
  const balanceEarnings = grossEarnings - basic - hra - overtimeWages;
  return {
    id,
    runId: RUN_ID,
    employeeId,
    presentDays,
    absentDays,
    leaveDays,
    weekOffDays,
    holidayPresentDays,
    payableDays,
    overtimeHours,
    basic,
    da: Math.round(balanceEarnings * 0.25),
    hra,
    conveyance: Math.round(balanceEarnings * 0.15),
    foodAllowance: Math.round(balanceEarnings * 0.15),
    nightAllowance: 0,
    overtimeWages,
    attendanceBonus: Math.round(balanceEarnings * 0.15),
    arrears: 0,
    holidayWages: holidayPresentDays ? Math.round(balanceEarnings * 0.1) : 0,
    productionIncentive: 0,
    medicalAllowance:
      balanceEarnings -
      Math.round(balanceEarnings * 0.25) -
      Math.round(balanceEarnings * 0.15) -
      Math.round(balanceEarnings * 0.15) -
      Math.round(balanceEarnings * 0.15) -
      (holidayPresentDays ? Math.round(balanceEarnings * 0.1) : 0),
    pfDeduction: Math.round(statutoryDeductions * 0.78),
    esiDeduction: Math.round(statutoryDeductions * 0.18),
    professionalTax: statutoryDeductions - Math.round(statutoryDeductions * 0.78) - Math.round(statutoryDeductions * 0.18),
    canteen: Math.round(otherDeductions * 0.35),
    advance: Math.round(otherDeductions * 0.45),
    otherDeduction: otherDeductions - Math.round(otherDeductions * 0.35) - Math.round(otherDeductions * 0.45),
    accommodationDeduction,
    returnAmount,
    grossEarnings,
    totalDeductions: statutoryDeductions + otherDeductions + accommodationDeduction,
    netPayable,
    validationStatus,
    validationMessage,
  };
}

async function loadAppData(access: AppAccess) {
  /* Supabase production databases intentionally start without demo payroll records. */
  const db = getDb();
  const [vendorRows, unitRows, employeeRows, runRows, itemRows, attendanceRows, chargeRows, auditRows, ruleRows, shiftRows, remarkRows, userRows] = await Promise.all([
    db.select().from(vendors).orderBy(asc(vendors.name)),
    db.select().from(clientUnits).orderBy(asc(clientUnits.clientName)),
    db.select().from(employees).orderBy(asc(employees.employeeCode)),
    db.select().from(payrollRuns).orderBy(asc(payrollRuns.payPeriod)),
    db.select({
      id: payrollItems.id,
      runId: payrollItems.runId,
      employeeId: payrollItems.employeeId,
      employeeCode: employees.employeeCode,
      employeeName: employees.name,
      department: employees.department,
      accommodationType: employees.accommodationType,
      roomNumber: employees.roomNumber,
      paymentMode: employees.paymentMode,
      bankAccountMasked: employees.bankAccountMasked,
      ifscMasked: employees.ifscMasked,
      complianceStatus: employees.complianceStatus,
      presentDays: payrollItems.presentDays,
      absentDays: payrollItems.absentDays,
      leaveDays: payrollItems.leaveDays,
      weekOffDays: payrollItems.weekOffDays,
      holidayPresentDays: payrollItems.holidayPresentDays,
      payableDays: payrollItems.payableDays,
      overtimeHours: payrollItems.overtimeHours,
      basic: payrollItems.basic,
      da: payrollItems.da,
      hra: payrollItems.hra,
      conveyance: payrollItems.conveyance,
      foodAllowance: payrollItems.foodAllowance,
      nightAllowance: payrollItems.nightAllowance,
      overtimeWages: payrollItems.overtimeWages,
      attendanceBonus: payrollItems.attendanceBonus,
      arrears: payrollItems.arrears,
      holidayWages: payrollItems.holidayWages,
      productionIncentive: payrollItems.productionIncentive,
      medicalAllowance: payrollItems.medicalAllowance,
      pfDeduction: payrollItems.pfDeduction,
      esiDeduction: payrollItems.esiDeduction,
      professionalTax: payrollItems.professionalTax,
      lwf: payrollItems.lwf,
      canteen: payrollItems.canteen,
      snacks: payrollItems.snacks,
      tent: payrollItems.tent,
      advance: payrollItems.advance,
      otherDeduction: payrollItems.otherDeduction,
      tds: payrollItems.tds,
      medicalInsurance: payrollItems.medicalInsurance,
      accommodationDeduction: payrollItems.accommodationDeduction,
      returnAmount: payrollItems.returnAmount,
      grossEarnings: payrollItems.grossEarnings,
      totalDeductions: payrollItems.totalDeductions,
      netPayable: payrollItems.netPayable,
      validationStatus: payrollItems.validationStatus,
      validationMessage: payrollItems.validationMessage,
    }).from(payrollItems).innerJoin(employees, eq(payrollItems.employeeId, employees.id)).orderBy(asc(employees.employeeCode)),
    db.select().from(attendanceEntries).orderBy(asc(attendanceEntries.attendanceDate), asc(attendanceEntries.employeeId)),
    db.select().from(accommodationCharges).orderBy(asc(accommodationCharges.roomNumber)),
    db.select().from(auditEvents).orderBy(desc(auditEvents.createdAt)).limit(30),
    db.select().from(payrollRules).orderBy(asc(payrollRules.vendorId)),
    db.select().from(shiftDefinitions).orderBy(asc(shiftDefinitions.name)),
    db.select().from(payrollRemarks).orderBy(asc(payrollRemarks.category), asc(payrollRemarks.title)),
    canView(access.profile.permissions, "users") ? db.select().from(appUsers).orderBy(asc(appUsers.fullName), asc(appUsers.email)) : Promise.resolve([]),
  ]);

  const permissions = access.profile.permissions;
  const seesAny = (modules: AccessModule[]) => modules.some((module) => canView(permissions, module));
  const seesOrganisation = seesAny(["dashboard", "payroll", "attendance", "employees", "accommodation", "payments", "clients", "masters", "settings"]);
  const seesEmployees = seesAny(["dashboard", "payroll", "attendance", "employees", "accommodation", "payments"]);
  const seesFullEmployeeDetails = seesAny(["payroll", "employees", "payments"]);
  const seesRuns = seesAny(["dashboard", "payroll", "attendance", "accommodation", "payments"]);
  const seesPayrollItems = seesRuns;
  const seesFullPayrollDetails = seesAny(["payroll", "payments"]);
  const seesPayrollSummaryMoney = seesAny(["dashboard", "accommodation"]);
  const seesRunMoney = seesAny(["dashboard", "payroll", "accommodation", "payments"]);

  const visibleEmployees = !seesEmployees ? [] : seesFullEmployeeDetails ? employeeRows : employeeRows.map((employee) => ({
    ...employee,
    uanMasked: null,
    esiMasked: null,
    bankAccountMasked: null,
    ifscMasked: null,
    bankName: null,
    salaryAmount: 0,
    salaryBasis: "monthly",
    paymentMode: "cash",
    complianceStatus: "ready",
  }));

  const visibleRuns = !seesRuns ? [] : seesRunMoney ? runRows : runRows.map((run) => ({
    ...run,
    grossEarnings: 0,
    statutoryDeductions: 0,
    otherDeductions: 0,
    accommodationDeductions: 0,
    netPayable: 0,
    bankPayable: 0,
    cashPayable: 0,
    issueCount: 0,
    approvedBy: null,
  }));

  const visibleItems = !seesPayrollItems ? [] : itemRows.map((item) => {
    if (seesFullPayrollDetails) return item;
    const redacted = { ...item };
    for (const field of [...earningFields, ...deductionFields]) redacted[field] = 0;
    redacted.bankAccountMasked = null;
    redacted.ifscMasked = null;
    redacted.paymentMode = "cash";
    if (!seesPayrollSummaryMoney) {
      redacted.accommodationDeduction = 0;
      redacted.returnAmount = 0;
      redacted.grossEarnings = 0;
      redacted.totalDeductions = 0;
      redacted.netPayable = 0;
    }
    if (!canView(permissions, "dashboard")) {
      redacted.validationStatus = "ready";
      redacted.validationMessage = null;
    }
    return redacted;
  });

  return {
    demo: vendorRows.every((vendor) => vendor.id === "vendor-jms" || vendor.id === "vendor-jcs"),
    vendors: seesOrganisation ? vendorRows : [],
    units: seesOrganisation ? unitRows : [],
    employees: visibleEmployees,
    runs: visibleRuns,
    payrollItems: visibleItems,
    attendance: canView(permissions, "attendance") ? attendanceRows : [],
    accommodationCharges: canView(permissions, "accommodation") ? chargeRows : [],
    auditEvents: seesAny(["dashboard", "users"]) ? auditRows.reverse() : [],
    rules: canView(permissions, "settings") ? ruleRows : [],
    shifts: seesAny(["masters", "attendance", "employees"]) ? shiftRows : [],
    remarks: seesAny(["clients", "masters", "attendance", "employees"]) ? remarkRows : [],
    currentUser: access.profile,
    appUsers: userRows.map(appUserProfile),
  };
}

export async function GET(identity: AuthenticatedUser | null) {
  try {
    const db = getDb();
    const access = await requireAppAccess(db, identity);
    return Response.json(await loadAppData(access));
  } catch (error) {
    const messages = errorMessages(error);
    const status = error instanceof RequestError ? error.status : 500;
    const safeMessage = error instanceof RequestError ? error.message : messages.at(-1) ?? "Unable to load payroll data";
    if (status >= 500) console.error("Payroll application data failed to load", safeMessage.split("\n")[0]);
    return Response.json({ error: safeMessage }, { status });
  }
}

function textValue(value: unknown, label: string) {
  const result = typeof value === "string" ? value.trim() : "";
  if (!result) throw new RequestError(`${label} is required`);
  return result;
}

function optionalValue(value: unknown) {
  if (value === null || value === undefined) return null;
  const result = String(value).trim();
  return result || null;
}

function positiveValue(value: unknown, label: string, maximum = 100000000) {
  const result = numberValue(value);
  if (result < 0 || result > maximum) throw new RequestError(`${label} must be between 0 and ${maximum}`);
  return result;
}

function periodValue(value: unknown) {
  const result = textValue(value, "Payroll month");
  if (!/^\d{4}-(?:0[1-9]|1[0-2])$/.test(result)) throw new RequestError("Payroll month must be YYYY-MM");
  return result;
}

function periodRange(period: string) {
  const [year, month] = period.split("-").map(Number);
  const nextYear = month === 12 ? year + 1 : year;
  const nextMonth = month === 12 ? 1 : month + 1;
  return { start: `${period}-01`, end: `${nextYear}-${String(nextMonth).padStart(2, "0")}-01`, days: new Date(year, month, 0).getDate() };
}

async function activeRules(db: Db, vendorId: string) {
  const [rule] = await db.select().from(payrollRules).where(eq(payrollRules.vendorId, vendorId)).limit(1);
  return { ...defaultPayrollRules, ...rule };
}

async function requireRun(db: Db, runId: string, editable = false) {
  const [run] = await db.select().from(payrollRuns).where(eq(payrollRuns.id, runId)).limit(1);
  if (!run) throw new RequestError("Payroll run not found", 404);
  if (editable && run.status === "approved") throw new RequestError("This payroll run is approved. Reopen it before making changes.", 409);
  return run;
}

async function writeAudit(db: Db, action: string, entityType: string, entityId: string, summary: string, actorEmail: string | null) {
  await db.insert(auditEvents).values({ action, entityType, entityId, summary, actorEmail });
}

async function recalculateRun(db: Db, runId: string, recomputeAttendance = false) {
  const run = await requireRun(db, runId);
  const { start, end } = periodRange(run.payPeriod);
  const [rows, unitEmployees, periodAttendance, charges, rules] = await Promise.all([
    db.select().from(payrollItems).where(eq(payrollItems.runId, runId)),
    db.select().from(employees).where(eq(employees.clientUnitId, run.clientUnitId)),
    db.select().from(attendanceEntries).where(and(gte(attendanceEntries.attendanceDate, start), lt(attendanceEntries.attendanceDate, end))),
    db.select().from(accommodationCharges).where(eq(accommodationCharges.runId, runId)),
    activeRules(db, run.vendorId),
  ]);
  const employeeMap = new Map(unitEmployees.map((employee) => [employee.id, employee]));
  const chargeMap = new Map(charges.map((charge) => [charge.employeeId, charge]));
  const attendanceMap = new Map<string, typeof periodAttendance>();
  for (const entry of periodAttendance) {
    const collection = attendanceMap.get(entry.employeeId) ?? [];
    collection.push(entry);
    attendanceMap.set(entry.employeeId, collection);
  }

  const updatedRows: Array<PayrollItemRow & { paymentMode: string }> = [];
  for (const row of rows) {
    const employee = employeeMap.get(row.employeeId);
    if (!employee) continue;
    const entries = attendanceMap.get(employee.id) ?? [];
    const isUnchangedDemo = run.id === RUN_ID && entries.length > 0 && entries.every((entry) => entry.source === "demo");
    const shouldRecompute = recomputeAttendance && entries.length > 0 && !isUnchangedDemo;
    const next = { ...row };
    if (shouldRecompute) {
      Object.assign(next, attendanceSummary(entries, rules));
      if (employee.salaryAmount > 0) next.basic = salaryForAttendance(employee.salaryAmount, employee.salaryBasis, next.payableDays, rules);
      if (rules.overtimeHourlyRate > 0) next.overtimeWages = roundMoney(next.overtimeHours * rules.overtimeHourlyRate);
      if (rules.pfRate > 0) next.pfDeduction = roundMoney(next.basic * rules.pfRate / 100);
      if (rules.professionalTax > 0) next.professionalTax = rules.professionalTax;
      if (rules.lwf > 0) next.lwf = rules.lwf;
    }
    const accommodation = accommodationTotal(chargeMap.get(employee.id));
    if (chargeMap.has(employee.id)) Object.assign(next, accommodation);
    if (shouldRecompute && rules.esiRate > 0) next.esiDeduction = roundMoney(payrollTotals(next).grossEarnings * rules.esiRate / 100);
    const totals = payrollTotals(next);
    Object.assign(next, {
      grossEarnings: totals.grossEarnings,
      totalDeductions: totals.totalDeductions,
      netPayable: totals.netPayable,
      accommodationDeduction: totals.accommodationDeduction,
      returnAmount: totals.returnAmount,
    }, validationForEmployee(employee, rules));
    const { id, runId: ignoredRunId, employeeId: ignoredEmployeeId, ...values } = next;
    void ignoredRunId;
    void ignoredEmployeeId;
    await db.update(payrollItems).set(values).where(eq(payrollItems.id, id));
    if (employee.complianceStatus !== next.validationStatus) {
      await db.update(employees).set({ complianceStatus: next.validationStatus }).where(eq(employees.id, employee.id));
    }
    updatedRows.push({ ...next, paymentMode: employee.paymentMode });
  }

  const grossEarnings = roundMoney(updatedRows.reduce((sum, row) => sum + row.grossEarnings, 0));
  const statutoryDeductions = roundMoney(updatedRows.reduce((sum, row) => sum + row.pfDeduction + row.esiDeduction + row.professionalTax + row.lwf + row.tds, 0));
  const accommodationDeductions = roundMoney(updatedRows.reduce((sum, row) => sum + row.accommodationDeduction, 0));
  const totalDeductions = roundMoney(updatedRows.reduce((sum, row) => sum + row.totalDeductions, 0));
  const otherDeductions = roundMoney(totalDeductions - statutoryDeductions - accommodationDeductions);
  const netPayable = roundMoney(updatedRows.reduce((sum, row) => sum + row.netPayable, 0));
  const bankPayable = roundMoney(updatedRows.filter((row) => row.paymentMode === "bank").reduce((sum, row) => sum + row.netPayable, 0));
  const cashPayable = roundMoney(netPayable - bankPayable);
  const issueCount = updatedRows.filter((row) => row.validationStatus !== "ready").length;
  await db.update(payrollRuns).set({ employeeCount: updatedRows.length, grossEarnings, statutoryDeductions, otherDeductions, accommodationDeductions, netPayable, bankPayable, cashPayable, issueCount, status: run.status === "approved" ? "approved" : issueCount ? "needs_review" : "validated", updatedAt: new Date().toISOString() }).where(eq(payrollRuns.id, runId));
}

async function addEmployeesToRun(db: Db, run: PayrollRunRow, employeeRows: EmployeeRow[]) {
  if (!employeeRows.length) return;
  const existing = await db.select({ employeeId: payrollItems.employeeId }).from(payrollItems).where(eq(payrollItems.runId, run.id));
  const existingIds = new Set(existing.map((row) => row.employeeId));
  const rules = await activeRules(db, run.vendorId);
  const values = employeeRows.filter((employee) => employee.status === "active" && !existingIds.has(employee.id)).map((employee) => ({
    id: `ITEM-${crypto.randomUUID()}`,
    runId: run.id,
    employeeId: employee.id,
    ...validationForEmployee(employee, rules),
  }));
  for (let index = 0; index < values.length; index += 2) await db.insert(payrollItems).values(values.slice(index, index + 2));
}

async function createRun(db: Db, vendorId: string, unitId: string, period: string) {
  const [client] = await db.select().from(vendors).where(eq(vendors.id, vendorId)).limit(1);
  const [unit] = await db.select().from(clientUnits).where(eq(clientUnits.id, unitId)).limit(1);
  if (!client || !unit || unit.vendorId !== vendorId) throw new RequestError("Select a valid client and employer unit", 404);
  if (client.status !== "active" || unit.status !== "active") throw new RequestError("Reactivate the client and employer unit before creating payroll", 409);
  const [existing] = await db.select().from(payrollRuns).where(and(eq(payrollRuns.clientUnitId, unitId), eq(payrollRuns.payPeriod, period))).limit(1);
  if (existing) return existing;
  const id = `RUN-${period.replace("-", "")}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`;
  await db.insert(payrollRuns).values({ id, vendorId, clientUnitId: unitId, payPeriod: period, status: "draft" });
  const run = await requireRun(db, id);
  const assigned = await db.select().from(employees).where(and(eq(employees.clientUnitId, unitId), eq(employees.status, "active")));
  await addEmployeesToRun(db, run, assigned);
  await recalculateRun(db, id, true);
  return requireRun(db, id);
}

function employeeValues(payload: Record<string, unknown>, vendorId: string, unitId: string) {
  const employeeCode = textValue(payload.employeeCode, "Employee code").toUpperCase();
  const name = textValue(payload.name, "Employee name");
  const paymentMode = payload.paymentMode === "bank" ? "bank" : "cash";
  const accommodationType = ["Joy Room", "Outside Room", "Tamil Own"].includes(String(payload.accommodationType)) ? String(payload.accommodationType) : "Tamil Own";
  const dateOfJoining = textValue(payload.dateOfJoining, "Date of joining");
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateOfJoining)) throw new RequestError("Date of joining must be YYYY-MM-DD");
  return {
    vendorId,
    clientUnitId: unitId,
    employeeCode,
    name,
    department: textValue(payload.department, "Department"),
    dateOfJoining,
    uanMasked: optionalValue(payload.uanMasked),
    esiMasked: optionalValue(payload.esiMasked),
    bankAccountMasked: optionalValue(payload.bankAccountMasked),
    ifscMasked: optionalValue(payload.ifscMasked)?.toUpperCase() ?? null,
    bankName: optionalValue(payload.bankName),
    accommodationType,
    roomNumber: optionalValue(payload.roomNumber),
    paymentMode,
    salaryAmount: positiveValue(payload.salaryAmount, "Salary amount"),
    salaryBasis: payload.salaryBasis === "daily" ? "daily" : "monthly",
    defaultShift: optionalValue(payload.defaultShift) ?? "General",
    remarks: optionalValue(payload.remarks),
  };
}

async function updateUnitCount(db: Db, unitId: string) {
  const rows = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.clientUnitId, unitId), eq(employees.status, "active")));
  await db.update(clientUnits).set({ employeeCount: rows.length }).where(eq(clientUnits.id, unitId));
}

async function deleteEmployee(db: Db, employeeId: string) {
  const [employee] = await db.select().from(employees).where(eq(employees.id, employeeId)).limit(1);
  if (!employee) throw new RequestError("Employee not found", 404);
  const history = await db.select({ runId: payrollItems.runId, status: payrollRuns.status }).from(payrollItems)
    .innerJoin(payrollRuns, eq(payrollItems.runId, payrollRuns.id))
    .where(eq(payrollItems.employeeId, employeeId));
  if (history.some((row) => row.status === "approved")) {
    throw new RequestError("This employee belongs to approved payroll history. Make the employee inactive instead of deleting the record.", 409);
  }
  await db.delete(accommodationCharges).where(eq(accommodationCharges.employeeId, employeeId));
  await db.delete(attendanceEntries).where(eq(attendanceEntries.employeeId, employeeId));
  await db.delete(payrollItems).where(eq(payrollItems.employeeId, employeeId));
  await db.delete(employees).where(eq(employees.id, employeeId));
  await updateUnitCount(db, employee.clientUnitId);
  for (const runId of new Set(history.map((row) => row.runId))) await recalculateRun(db, runId, false);
  return employee;
}

async function importWorkbook(db: Db, payload: Payload, actorEmail: string | null) {
  const vendorId = textValue(payload.vendorId, "Payroll entity");
  const unitId = textValue(payload.unitId, "Client unit");
  const period = periodValue(payload.payPeriod);
  const sourceType = String(payload.sourceType ?? "attendance");
  const importedEmployees = Array.isArray(payload.employees) ? payload.employees as Array<Record<string, unknown>> : [];
  const importedAttendance = Array.isArray(payload.attendance) ? payload.attendance as Array<Record<string, unknown>> : [];
  const importedItems = Array.isArray(payload.salaryItems) ? payload.salaryItems as Array<Record<string, unknown>> : [];
  if (!importedEmployees.length) throw new RequestError("No employee rows were found in the uploaded file");
  if (importedEmployees.length > 1000 || importedAttendance.length > 35000) throw new RequestError("Import exceeds the limit of 1,000 employees or 35,000 attendance entries");
  const run = await createRun(db, vendorId, unitId, period);
  await requireRun(db, run.id, true);

  const allEmployees = await db.select().from(employees);
  const existingByCode = new Map(allEmployees.map((employee) => [employee.employeeCode.toUpperCase(), employee]));
  const newRows: Array<typeof employees.$inferInsert> = [];
  for (const imported of importedEmployees) {
    if (!imported.employeeCode || !imported.name) continue;
    const code = String(imported.employeeCode).trim().toUpperCase();
    const existing = existingByCode.get(code);
    if (existing && existing.clientUnitId !== unitId) throw new RequestError(`Employee ${code} is already assigned to another client unit`, 409);
    if (existing) {
      if (sourceType === "salary") {
        const update = employeeValues({ ...existing, ...imported }, vendorId, unitId);
        await db.update(employees).set(update).where(eq(employees.id, existing.id));
      }
      continue;
    }
    const value = employeeValues({ department: "General", dateOfJoining: `${period}-01`, salaryAmount: 0, paymentMode: "cash", accommodationType: "Tamil Own", ...imported }, vendorId, unitId);
    const employee = { id: `EMP-${crypto.randomUUID()}`, ...value, complianceStatus: "ready", status: "active" };
    newRows.push(employee);
    existingByCode.set(code, employee as EmployeeRow);
  }
  for (let index = 0; index < newRows.length; index += 4) await db.insert(employees).values(newRows.slice(index, index + 4));

  const assigned = await db.select().from(employees).where(eq(employees.clientUnitId, unitId));
  const employeeByCode = new Map(assigned.map((employee) => [employee.employeeCode.toUpperCase(), employee]));
  await addEmployeesToRun(db, run, assigned);

  if (importedAttendance.length) {
    const { start, end, days } = periodRange(period);
    const existingAttendance = await db.select().from(attendanceEntries).where(and(gte(attendanceEntries.attendanceDate, start), lt(attendanceEntries.attendanceDate, end)));
    const existingMap = new Map(existingAttendance.map((entry) => [`${entry.employeeId}:${entry.attendanceDate}`, entry.id]));
    const statements: ReturnType<ReturnType<typeof getRawDb>["prepare"]>[] = [];
    const d1 = getRawDb();
    for (const entry of importedAttendance) {
      const employee = employeeByCode.get(String(entry.employeeCode ?? "").trim().toUpperCase());
      const date = String(entry.attendanceDate ?? "");
      const status = String(entry.statusCode ?? "").toUpperCase();
      if (!employee || !date.startsWith(`${period}-`) || !ATTENDANCE_CODES.includes(status as (typeof ATTENDANCE_CODES)[number])) continue;
      const day = Number(date.slice(8));
      if (day < 1 || day > days) continue;
      const shift = optionalValue(entry.shiftCode) ?? employee.defaultShift;
      const overtime = positiveValue(entry.overtimeHours, "Overtime hours", 24);
      const current = existingMap.get(`${employee.id}:${date}`);
      if (current) statements.push(d1.prepare("UPDATE attendance_entries SET status_code = ?, shift_code = ?, overtime_hours = ?, source = ?, updated_by = ?, updated_at = ? WHERE id = ?").bind(status, shift, overtime, "import", actorEmail, new Date().toISOString(), current));
      else statements.push(d1.prepare("INSERT INTO attendance_entries (employee_id, attendance_date, status_code, shift_code, overtime_hours, source, updated_by, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").bind(employee.id, date, status, shift, overtime, "import", actorEmail, new Date().toISOString()));
    }
    for (let index = 0; index < statements.length; index += 75) await d1.batch(statements.slice(index, index + 75));
  }

  if (importedItems.length) {
    const itemRows = await db.select().from(payrollItems).where(eq(payrollItems.runId, run.id));
    const itemByEmployee = new Map(itemRows.map((row) => [row.employeeId, row]));
    for (const imported of importedItems) {
      const employee = employeeByCode.get(String(imported.employeeCode ?? "").trim().toUpperCase());
      const item = employee ? itemByEmployee.get(employee.id) : null;
      if (!employee || !item) continue;
      const update: Record<string, number> = {};
      for (const field of [...earningFields, ...deductionFields]) if (Object.hasOwn(imported, field)) update[field] = positiveValue(imported[field], field);
      for (const field of ["presentDays", "payableDays", "overtimeHours"] as const) if (Object.hasOwn(imported, field)) update[field] = positiveValue(imported[field], field);
      const totals = payrollTotals({ ...item, ...update });
      await db.update(payrollItems).set({ ...update, grossEarnings: totals.grossEarnings, totalDeductions: totals.totalDeductions, netPayable: totals.netPayable }).where(eq(payrollItems.id, item.id));
    }
  }

  await updateUnitCount(db, unitId);
  await recalculateRun(db, run.id, importedAttendance.length > 0);
  await writeAudit(db, "workbook_imported", "payroll_run", run.id, `Imported ${importedEmployees.length} employees and ${importedAttendance.length} attendance entries from ${sourceType} workbook`, actorEmail);
  return run.id;
}

async function activeSuperAdminCount(db: Db, excludeId?: string) {
  const rows = await db.select({ id: appUsers.id, role: appUsers.role, status: appUsers.status }).from(appUsers);
  return rows.filter((row) => row.id !== excludeId && row.role === "super_admin" && row.status === "active").length;
}

function permissionPayload(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" ? value as Record<string, unknown> : {};
}

async function saveAppUser(db: Db, payload: Payload, access: AppAccess) {
  requireSuperAdmin(access);
  const existingId = optionalValue(payload.id);
  const email = textValue(payload.email, "User email").toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new RequestError("Enter a valid user email address");
  const fullName = optionalValue(payload.fullName);
  const role = normalizeRole(payload.role);
  const permissions = normalizePermissions(role, permissionPayload(payload.permissions));
  const canApprovePayroll = role === "super_admin" || payload.canApprovePayroll === true || payload.canApprovePayroll === 1 || payload.canApprovePayroll === "on";
  const now = new Date().toISOString();
  const values = { email, fullName, role, permissionsJson: JSON.stringify(permissions), canApprovePayroll: canApprovePayroll ? 1 : 0, updatedAt: now };
  const [emailOwner] = await db.select({ id: appUsers.id }).from(appUsers).where(eq(appUsers.email, email)).limit(1);
  if (emailOwner && emailOwner.id !== existingId) throw new RequestError("A user profile already exists for this email address", 409);
  if (existingId) {
    const [existing] = await db.select().from(appUsers).where(eq(appUsers.id, existingId)).limit(1);
    if (!existing) throw new RequestError("User profile not found", 404);
    if (existing.email === access.identity.email.toLowerCase() && (email !== existing.email || role !== "super_admin")) throw new RequestError("You cannot change your own Super Admin identity or role", 409);
    if (existing.role === "super_admin" && existing.status === "active" && role !== "super_admin" && await activeSuperAdminCount(db, existing.id) === 0) throw new RequestError("Create another active Super Admin before changing this role", 409);
    await db.update(appUsers).set(values).where(eq(appUsers.id, existingId));
    await writeAudit(db, "user_updated", "app_user", existingId, `Updated ${email} as ${role.replaceAll("_", " ")}`, access.identity.email);
    return;
  }
  const id = `USER-${crypto.randomUUID()}`;
  await db.insert(appUsers).values({ id, ...values, status: "active", createdBy: access.identity.email, createdAt: now });
  await writeAudit(db, "user_created", "app_user", id, `Added ${email} as ${role.replaceAll("_", " ")}`, access.identity.email);
}

export async function POST(request: Request, identity: AuthenticatedUser | null) {
  try {
    const payload = (await request.json()) as Payload;
    const action = textValue(payload.action, "Action");
    const db = getDb();
    const access = await requireAppAccess(db, identity);
    /* Supabase production databases intentionally start without demo payroll records. */
    if (action === "approve") {
      requireModule(access, "payroll", "manage");
      if (!access.profile.canApprovePayroll) throw new RequestError("Your profile can process payroll but does not have final approval authority", 403);
    } else {
      const required = actionPermission(action, payload);
      if (required) requireModule(access, required.module, required.level);
    }
    if (action === "save-app-user" || ((action === "set-record-status" || action === "delete-record") && payload.entityType === "app_user")) requireSuperAdmin(access);
    const user = access.identity;
    const actorEmail = user.email;
    let runId = typeof payload.runId === "string" ? payload.runId : RUN_ID;

    if (action === "save-app-user") {
      await saveAppUser(db, payload, access);
    } else if (action === "create-vendor" || action === "save-client") {
      const code = textValue(payload.code, "Client code").toUpperCase();
      if (!/^[A-Z0-9_-]{2,15}$/.test(code)) throw new RequestError("Client code must contain 2–15 letters, numbers, underscores, or hyphens");
      const existingId = optionalValue(payload.id);
      const id = existingId ?? `CLIENT-${crypto.randomUUID()}`;
      const name = textValue(payload.name, "Client name");
      const values = { code, name, legalName: optionalValue(payload.legalName) ?? name, epfCode: optionalValue(payload.epfCode), esiCode: optionalValue(payload.esiCode), gstin: optionalValue(payload.gstin)?.toUpperCase() ?? null, remarks: optionalValue(payload.remarks) };
      if (existingId) {
        const [existing] = await db.select({ id: vendors.id }).from(vendors).where(eq(vendors.id, existingId)).limit(1);
        if (!existing) throw new RequestError("Client not found", 404);
        await db.update(vendors).set(values).where(eq(vendors.id, existingId));
      } else {
        await db.insert(vendors).values({ id, ...values });
        await createDefaultShifts(db, id);
      }
      await writeAudit(db, existingId ? "client_updated" : "client_created", "client", id, `${existingId ? "Updated" : "Added"} client ${name}`, actorEmail);
    } else if (action === "create-unit" || action === "save-unit") {
      const vendorId = textValue(payload.vendorId, "Client");
      const [client] = await db.select().from(vendors).where(eq(vendors.id, vendorId)).limit(1);
      if (!client) throw new RequestError("Client not found", 404);
      const existingId = optionalValue(payload.id);
      const id = existingId ?? `UNIT-${crypto.randomUUID()}`;
      const clientName = textValue(payload.clientName, "Employer name");
      const unitName = textValue(payload.unitName, "Unit name");
      const values = { vendorId, clientName, unitName, location: textValue(payload.location, "Location"), remarks: optionalValue(payload.remarks) };
      if (existingId) {
        const [existing] = await db.select().from(clientUnits).where(eq(clientUnits.id, existingId)).limit(1);
        if (!existing) throw new RequestError("Employer unit not found", 404);
        if (existing.vendorId !== vendorId) {
          const assigned = await db.select({ id: employees.id }).from(employees).where(eq(employees.clientUnitId, existingId)).limit(1);
          const runs = await db.select({ id: payrollRuns.id }).from(payrollRuns).where(eq(payrollRuns.clientUnitId, existingId)).limit(1);
          if (assigned.length || runs.length) throw new RequestError("An employer unit with employees or payroll history cannot be moved to another client.", 409);
        }
        await db.update(clientUnits).set(values).where(eq(clientUnits.id, existingId));
      } else {
        if (client.status !== "active") throw new RequestError("Reactivate the client before adding an employer unit", 409);
        await db.insert(clientUnits).values({ id, ...values, employeeCount: 0 });
      }
      await writeAudit(db, existingId ? "unit_updated" : "unit_created", "client_unit", id, `${existingId ? "Updated" : "Added"} ${clientName} · ${unitName}`, actorEmail);
    } else if (action === "save-employee") {
      const vendorId = textValue(payload.vendorId, "Client");
      const unitId = textValue(payload.unitId, "Employer unit");
      const [unit] = await db.select().from(clientUnits).where(eq(clientUnits.id, unitId)).limit(1);
      if (!unit || unit.vendorId !== vendorId) throw new RequestError("Select a valid client and employer unit", 404);
      const form = typeof payload.employee === "object" && payload.employee !== null ? payload.employee as Record<string, unknown> : payload;
      const values = employeeValues(form, vendorId, unitId);
      const rules = await activeRules(db, vendorId);
      const complianceStatus = validationForEmployee({ ...values, salaryAmount: values.salaryAmount }, rules).validationStatus;
      const employeeId = optionalValue(form.id);
      const id = employeeId ?? `EMP-${crypto.randomUUID()}`;
      if (employeeId) {
        const [existing] = await db.select().from(employees).where(eq(employees.id, employeeId)).limit(1);
        if (!existing || existing.clientUnitId !== unitId) throw new RequestError("Employee not found in the selected unit", 404);
        await db.update(employees).set({ ...values, complianceStatus }).where(eq(employees.id, employeeId));
      } else {
        await db.insert(employees).values({ id, ...values, complianceStatus });
      }
      const [saved] = await db.select().from(employees).where(eq(employees.id, id)).limit(1);
      const openRuns = await db.select().from(payrollRuns).where(eq(payrollRuns.clientUnitId, unitId));
      for (const run of openRuns.filter((candidate) => candidate.status !== "approved")) {
        await addEmployeesToRun(db, run, [saved]);
        await recalculateRun(db, run.id, true);
      }
      await updateUnitCount(db, unitId);
      await writeAudit(db, employeeId ? "employee_updated" : "employee_created", "employee", id, `${employeeId ? "Updated" : "Added"} ${values.name} (${values.employeeCode})`, actorEmail);
    } else if (action === "save-shift") {
      const vendorId = textValue(payload.vendorId, "Client");
      const [client] = await db.select().from(vendors).where(eq(vendors.id, vendorId)).limit(1);
      if (!client) throw new RequestError("Client not found", 404);
      const existingId = optionalValue(payload.id);
      const id = existingId ?? `SHIFT-${crypto.randomUUID()}`;
      const name = textValue(payload.name, "Shift name");
      const startTime = textValue(payload.startTime, "Shift start time");
      const endTime = textValue(payload.endTime, "Shift end time");
      if (![startTime, endTime].every((value) => /^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value))) throw new RequestError("Shift times must use the 24-hour HH:MM format");
      const values = { vendorId, name, startTime, endTime, remarks: optionalValue(payload.remarks) };
      if (existingId) {
        const [existing] = await db.select().from(shiftDefinitions).where(eq(shiftDefinitions.id, existingId)).limit(1);
        if (!existing || existing.vendorId !== vendorId) throw new RequestError("Shift not found for this client", 404);
        await db.update(shiftDefinitions).set(values).where(eq(shiftDefinitions.id, existingId));
        if (existing.name !== name) {
          await db.update(employees).set({ defaultShift: name }).where(and(eq(employees.vendorId, vendorId), eq(employees.defaultShift, existing.name)));
          const assigned = await db.select({ id: employees.id }).from(employees).where(eq(employees.vendorId, vendorId));
          if (assigned.length) await db.update(attendanceEntries).set({ shiftCode: name }).where(and(eq(attendanceEntries.shiftCode, existing.name), inArray(attendanceEntries.employeeId, assigned.map((employee) => employee.id))));
        }
      } else {
        await db.insert(shiftDefinitions).values({ id, ...values });
      }
      await writeAudit(db, existingId ? "shift_updated" : "shift_created", "shift", id, `${existingId ? "Updated" : "Added"} ${name} (${startTime}–${endTime})`, actorEmail);
    } else if (action === "save-remark") {
      const vendorId = textValue(payload.vendorId, "Client");
      const [client] = await db.select().from(vendors).where(eq(vendors.id, vendorId)).limit(1);
      if (!client) throw new RequestError("Client not found", 404);
      const existingId = optionalValue(payload.id);
      const id = existingId ?? `REMARK-${crypto.randomUUID()}`;
      const title = textValue(payload.title, "Remark title");
      const category = textValue(payload.category ?? "general", "Remark category").toLowerCase();
      if (!["general", "attendance", "employee", "salary", "employer", "shift"].includes(category)) throw new RequestError("Choose a supported remark category");
      const values = { vendorId, title, category, notes: optionalValue(payload.notes) };
      if (existingId) {
        const [existing] = await db.select().from(payrollRemarks).where(eq(payrollRemarks.id, existingId)).limit(1);
        if (!existing || existing.vendorId !== vendorId) throw new RequestError("Remark not found for this client", 404);
        await db.update(payrollRemarks).set(values).where(eq(payrollRemarks.id, existingId));
      } else {
        await db.insert(payrollRemarks).values({ id, ...values });
      }
      await writeAudit(db, existingId ? "remark_updated" : "remark_created", "remark", id, `${existingId ? "Updated" : "Added"} ${category} remark: ${title}`, actorEmail);
    } else if (action === "set-record-status") {
      const entityType = textValue(payload.entityType, "Record type");
      const entityId = textValue(payload.entityId, "Record");
      const status = textValue(payload.status, "Status");
      if (!["active", "inactive"].includes(status)) throw new RequestError("Status must be active or inactive");
      if (entityType === "app_user") {
        const [record] = await db.select().from(appUsers).where(eq(appUsers.id, entityId)).limit(1);
        if (!record) throw new RequestError("User profile not found", 404);
        if (record.email === access.identity.email.toLowerCase() && status === "inactive") throw new RequestError("You cannot make your own Super Admin profile inactive", 409);
        if (record.role === "super_admin" && record.status === "active" && status === "inactive" && await activeSuperAdminCount(db, record.id) === 0) throw new RequestError("Create another active Super Admin before deactivating this profile", 409);
        await db.update(appUsers).set({ status, updatedAt: new Date().toISOString() }).where(eq(appUsers.id, entityId));
        await writeAudit(db, `user_${status}`, "app_user", entityId, `${status === "active" ? "Reactivated" : "Made inactive"} user ${record.email}`, actorEmail);
      } else if (entityType === "client") {
        const [record] = await db.select().from(vendors).where(eq(vendors.id, entityId)).limit(1);
        if (!record) throw new RequestError("Client not found", 404);
        await db.update(vendors).set({ status }).where(eq(vendors.id, entityId));
        await writeAudit(db, `client_${status}`, "client", entityId, `${status === "active" ? "Reactivated" : "Made inactive"} client ${record.name}`, actorEmail);
      } else if (entityType === "unit") {
        const [record] = await db.select().from(clientUnits).where(eq(clientUnits.id, entityId)).limit(1);
        if (!record) throw new RequestError("Employer unit not found", 404);
        await db.update(clientUnits).set({ status }).where(eq(clientUnits.id, entityId));
        await writeAudit(db, `unit_${status}`, "client_unit", entityId, `${status === "active" ? "Reactivated" : "Made inactive"} employer unit ${record.clientName} · ${record.unitName}`, actorEmail);
      } else if (entityType === "employee") {
        const [record] = await db.select().from(employees).where(eq(employees.id, entityId)).limit(1);
        if (!record) throw new RequestError("Employee not found", 404);
        await db.update(employees).set({ status }).where(eq(employees.id, entityId));
        if (status === "active") {
          const [reactivated] = await db.select().from(employees).where(eq(employees.id, entityId)).limit(1);
          const openRuns = await db.select().from(payrollRuns).where(eq(payrollRuns.clientUnitId, record.clientUnitId));
          for (const run of openRuns.filter((candidate) => candidate.status !== "approved")) {
            await addEmployeesToRun(db, run, [reactivated]);
            await recalculateRun(db, run.id, true);
          }
        }
        await updateUnitCount(db, record.clientUnitId);
        await writeAudit(db, `employee_${status}`, "employee", entityId, `${status === "active" ? "Reactivated" : "Made inactive"} ${record.name} (${record.employeeCode})`, actorEmail);
      } else if (entityType === "shift") {
        const [record] = await db.select().from(shiftDefinitions).where(eq(shiftDefinitions.id, entityId)).limit(1);
        if (!record) throw new RequestError("Shift not found", 404);
        if (status === "inactive") {
          const assigned = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.vendorId, record.vendorId), eq(employees.defaultShift, record.name), eq(employees.status, "active")));
          if (assigned.length) {
            const alternatives = await db.select().from(shiftDefinitions).where(and(eq(shiftDefinitions.vendorId, record.vendorId), eq(shiftDefinitions.status, "active")));
            const replacement = alternatives.find((shift) => shift.id !== record.id);
            if (!replacement) throw new RequestError("Create another active shift before deactivating a shift assigned to employees", 409);
            await db.update(employees).set({ defaultShift: replacement.name }).where(and(eq(employees.vendorId, record.vendorId), eq(employees.defaultShift, record.name), eq(employees.status, "active")));
          }
        }
        await db.update(shiftDefinitions).set({ status }).where(eq(shiftDefinitions.id, entityId));
        await writeAudit(db, `shift_${status}`, "shift", entityId, `${status === "active" ? "Reactivated" : "Made inactive"} shift ${record.name}`, actorEmail);
      } else if (entityType === "remark") {
        const [record] = await db.select().from(payrollRemarks).where(eq(payrollRemarks.id, entityId)).limit(1);
        if (!record) throw new RequestError("Remark not found", 404);
        await db.update(payrollRemarks).set({ status }).where(eq(payrollRemarks.id, entityId));
        await writeAudit(db, `remark_${status}`, "remark", entityId, `${status === "active" ? "Reactivated" : "Made inactive"} remark ${record.title}`, actorEmail);
      } else {
        throw new RequestError(`Unsupported record type: ${entityType}`);
      }
    } else if (action === "delete-record") {
      const entityType = textValue(payload.entityType, "Record type");
      const entityId = textValue(payload.entityId, "Record");
      if (entityType === "app_user") {
        const [record] = await db.select().from(appUsers).where(eq(appUsers.id, entityId)).limit(1);
        if (!record) throw new RequestError("User profile not found", 404);
        if (record.email === access.identity.email.toLowerCase()) throw new RequestError("You cannot delete your own Super Admin profile", 409);
        if (record.role === "super_admin" && record.status === "active" && await activeSuperAdminCount(db, record.id) === 0) throw new RequestError("Create another active Super Admin before deleting this profile", 409);
        await db.delete(appUsers).where(eq(appUsers.id, entityId));
        await writeAudit(db, "user_deleted", "app_user", entityId, `Deleted access profile ${record.email}`, actorEmail);
      } else if (entityType === "employee") {
        const record = await deleteEmployee(db, entityId);
        await writeAudit(db, "employee_deleted", "employee", entityId, `Deleted ${record.name} (${record.employeeCode})`, actorEmail);
      } else if (entityType === "unit") {
        const [record] = await db.select().from(clientUnits).where(eq(clientUnits.id, entityId)).limit(1);
        if (!record) throw new RequestError("Employer unit not found", 404);
        const assigned = await db.select({ id: employees.id }).from(employees).where(eq(employees.clientUnitId, entityId)).limit(1);
        const history = await db.select({ id: payrollRuns.id }).from(payrollRuns).where(eq(payrollRuns.clientUnitId, entityId)).limit(1);
        if (assigned.length || history.length) throw new RequestError("This employer unit has employees or payroll history. Remove those records first, or make the employer unit inactive.", 409);
        await db.delete(clientUnits).where(eq(clientUnits.id, entityId));
        await writeAudit(db, "unit_deleted", "client_unit", entityId, `Deleted employer unit ${record.clientName} · ${record.unitName}`, actorEmail);
      } else if (entityType === "client") {
        const [record] = await db.select().from(vendors).where(eq(vendors.id, entityId)).limit(1);
        if (!record) throw new RequestError("Client not found", 404);
        const units = await db.select({ id: clientUnits.id }).from(clientUnits).where(eq(clientUnits.vendorId, entityId)).limit(1);
        if (units.length) throw new RequestError("This client still has employer units. Delete the units first, or make the client inactive.", 409);
        await db.delete(payrollRules).where(eq(payrollRules.vendorId, entityId));
        await db.delete(payrollRemarks).where(eq(payrollRemarks.vendorId, entityId));
        await db.delete(shiftDefinitions).where(eq(shiftDefinitions.vendorId, entityId));
        await db.delete(vendors).where(eq(vendors.id, entityId));
        await writeAudit(db, "client_deleted", "client", entityId, `Deleted client ${record.name}`, actorEmail);
      } else if (entityType === "shift") {
        const [record] = await db.select().from(shiftDefinitions).where(eq(shiftDefinitions.id, entityId)).limit(1);
        if (!record) throw new RequestError("Shift not found", 404);
        const assigned = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.vendorId, record.vendorId), eq(employees.defaultShift, record.name)));
        if (assigned.length) {
          const alternatives = await db.select().from(shiftDefinitions).where(and(eq(shiftDefinitions.vendorId, record.vendorId), eq(shiftDefinitions.status, "active")));
          const replacement = alternatives.find((shift) => shift.id !== record.id);
          if (!replacement) throw new RequestError("Create another active shift before deleting a shift assigned to employees", 409);
          await db.update(employees).set({ defaultShift: replacement.name }).where(and(eq(employees.vendorId, record.vendorId), eq(employees.defaultShift, record.name)));
        }
        await db.delete(shiftDefinitions).where(eq(shiftDefinitions.id, entityId));
        await writeAudit(db, "shift_deleted", "shift", entityId, `Deleted shift ${record.name}; existing attendance history was preserved`, actorEmail);
      } else if (entityType === "remark") {
        const [record] = await db.select().from(payrollRemarks).where(eq(payrollRemarks.id, entityId)).limit(1);
        if (!record) throw new RequestError("Remark not found", 404);
        await db.delete(payrollRemarks).where(eq(payrollRemarks.id, entityId));
        await writeAudit(db, "remark_deleted", "remark", entityId, `Deleted ${record.category} remark ${record.title}`, actorEmail);
      } else {
        throw new RequestError(`Unsupported record type: ${entityType}`);
      }
    } else if (action === "create-run") {
      const vendorId = textValue(payload.vendorId, "Payroll entity");
      const unitId = textValue(payload.unitId, "Client unit");
      const period = periodValue(payload.payPeriod);
      const existing = await db.select().from(payrollRuns).where(and(eq(payrollRuns.clientUnitId, unitId), eq(payrollRuns.payPeriod, period))).limit(1);
      if (existing.length) throw new RequestError(`A payroll run already exists for ${period}`, 409);
      const run = await createRun(db, vendorId, unitId, period);
      runId = run.id;
      await writeAudit(db, "run_created", "payroll_run", run.id, `Created ${period} payroll with ${run.employeeCount} employees`, actorEmail);
    } else if (action === "save-attendance") {
      const run = await requireRun(db, runId, true);
      const employeeId = textValue(payload.employeeId, "Employee");
      const attendanceDate = textValue(payload.attendanceDate, "Attendance date");
      const { days } = periodRange(run.payPeriod);
      if (!attendanceDate.startsWith(`${run.payPeriod}-`) || Number(attendanceDate.slice(8)) < 1 || Number(attendanceDate.slice(8)) > days) throw new RequestError("Attendance date must belong to the selected payroll month");
      const [employee] = await db.select().from(employees).where(eq(employees.id, employeeId)).limit(1);
      if (!employee || employee.clientUnitId !== run.clientUnitId) throw new RequestError("Employee does not belong to this payroll run", 404);
      const statusCode = textValue(payload.statusCode, "Attendance status").toUpperCase();
      if (!ATTENDANCE_CODES.includes(statusCode as (typeof ATTENDANCE_CODES)[number])) throw new RequestError("Unsupported attendance status");
      if (employee.status !== "active") throw new RequestError("Reactivate the employee before recording attendance", 409);
      const values = { statusCode, shiftCode: optionalValue(payload.shiftCode) ?? employee.defaultShift, overtimeHours: positiveValue(payload.overtimeHours, "Overtime hours", 24), remarks: optionalValue(payload.remarks), source: "manual", updatedBy: actorEmail, updatedAt: new Date().toISOString() };
      const [existing] = await db.select().from(attendanceEntries).where(and(eq(attendanceEntries.employeeId, employeeId), eq(attendanceEntries.attendanceDate, attendanceDate))).limit(1);
      if (existing) await db.update(attendanceEntries).set(values).where(eq(attendanceEntries.id, existing.id));
      else await db.insert(attendanceEntries).values({ employeeId, attendanceDate, ...values });
      await recalculateRun(db, runId, true);
      await writeAudit(db, "attendance_saved", "attendance", employeeId, `Updated ${employee.employeeCode} attendance on ${attendanceDate} to ${statusCode}`, actorEmail);
    } else if (action === "delete-attendance") {
      const run = await requireRun(db, runId, true);
      const employeeId = textValue(payload.employeeId, "Employee");
      const attendanceDate = textValue(payload.attendanceDate, "Attendance date");
      const [employee] = await db.select().from(employees).where(eq(employees.id, employeeId)).limit(1);
      if (!employee || employee.clientUnitId !== run.clientUnitId) throw new RequestError("Employee does not belong to this payroll run", 404);
      await db.delete(attendanceEntries).where(and(eq(attendanceEntries.employeeId, employeeId), eq(attendanceEntries.attendanceDate, attendanceDate)));
      await recalculateRun(db, runId, true);
      await writeAudit(db, "attendance_deleted", "attendance", employeeId, `Deleted ${employee.employeeCode} attendance on ${attendanceDate}`, actorEmail);
    } else if (action === "save-payroll-item") {
      await requireRun(db, runId, true);
      const itemId = textValue(payload.itemId, "Employee salary record");
      const [item] = await db.select().from(payrollItems).where(and(eq(payrollItems.id, itemId), eq(payrollItems.runId, runId))).limit(1);
      if (!item) throw new RequestError("Salary record not found", 404);
      const fields = typeof payload.fields === "object" && payload.fields !== null ? payload.fields as Record<string, unknown> : {};
      const update: Record<string, number> = {};
      for (const field of [...earningFields, ...deductionFields]) if (Object.hasOwn(fields, field)) update[field] = positiveValue(fields[field], field);
      const totals = payrollTotals({ ...item, ...update });
      await db.update(payrollItems).set({ ...update, grossEarnings: totals.grossEarnings, totalDeductions: totals.totalDeductions, netPayable: totals.netPayable }).where(eq(payrollItems.id, itemId));
      await recalculateRun(db, runId, false);
      await writeAudit(db, "salary_updated", "payroll_item", itemId, "Updated employee earnings and deductions", actorEmail);
    } else if (action === "save-accommodation") {
      const run = await requireRun(db, runId, true);
      const employeeId = textValue(payload.employeeId, "Employee");
      const [employee] = await db.select().from(employees).where(eq(employees.id, employeeId)).limit(1);
      if (!employee || employee.clientUnitId !== run.clientUnitId) throw new RequestError("Employee not found in this unit", 404);
      const fields = typeof payload.fields === "object" && payload.fields !== null ? payload.fields as Record<string, unknown> : {};
      const numericFields = ["idCard", "rent", "bus", "medical", "ticket", "shoe", "advance", "food", "aadhaarUpdate", "bankAccountCharge", "tshirt", "oldPending", "rationShare", "returnAmount"] as const;
      const values: Record<string, string | number | null> = { roomNumber: optionalValue(fields.roomNumber) ?? employee.roomNumber };
      for (const field of numericFields) values[field] = positiveValue(fields[field], field);
      const [existing] = await db.select().from(accommodationCharges).where(and(eq(accommodationCharges.runId, runId), eq(accommodationCharges.employeeId, employeeId))).limit(1);
      if (existing) await db.update(accommodationCharges).set(values).where(eq(accommodationCharges.id, existing.id));
      else await db.insert(accommodationCharges).values({ runId, employeeId, ...values });
      await recalculateRun(db, runId, false);
      await writeAudit(db, "accommodation_updated", "employee", employeeId, `Updated accommodation recoveries for ${employee.employeeCode}`, actorEmail);
    } else if (action === "delete-accommodation") {
      await requireRun(db, runId, true);
      const employeeId = textValue(payload.employeeId, "Employee");
      await db.delete(accommodationCharges).where(and(eq(accommodationCharges.runId, runId), eq(accommodationCharges.employeeId, employeeId)));
      await db.update(payrollItems).set({ accommodationDeduction: 0, returnAmount: 0 }).where(and(eq(payrollItems.runId, runId), eq(payrollItems.employeeId, employeeId)));
      await recalculateRun(db, runId, false);
      await writeAudit(db, "accommodation_deleted", "employee", employeeId, "Deleted accommodation recoveries", actorEmail);
    } else if (action === "save-rules") {
      const vendorId = textValue(payload.vendorId, "Payroll entity");
      const fields = typeof payload.rules === "object" && payload.rules !== null ? payload.rules as Record<string, unknown> : {};
      const standardWorkingDays = positiveValue(fields.standardWorkingDays, "Working days", 31);
      if (standardWorkingDays < 1 || !Number.isInteger(standardWorkingDays)) throw new RequestError("Working days must be a whole number between 1 and 31");
      const effectiveFrom = textValue(fields.effectiveFrom, "Effective date");
      if (!/^\d{4}-\d{2}-\d{2}$/.test(effectiveFrom)) throw new RequestError("Effective date must be YYYY-MM-DD");
      const values = { standardWorkingDays, pfRate: positiveValue(fields.pfRate, "PF rate", 100), esiRate: positiveValue(fields.esiRate, "ESI rate", 100), professionalTax: positiveValue(fields.professionalTax, "Professional tax"), lwf: positiveValue(fields.lwf, "LWF"), overtimeHourlyRate: positiveValue(fields.overtimeHourlyRate, "Overtime rate"), paidLeave: fields.paidLeave ? 1 : 0, paidWeekOff: fields.paidWeekOff ? 1 : 0, effectiveFrom, updatedAt: new Date().toISOString() };
      const [existing] = await db.select().from(payrollRules).where(eq(payrollRules.vendorId, vendorId)).limit(1);
      if (existing) await db.update(payrollRules).set(values).where(eq(payrollRules.id, existing.id));
      else await db.insert(payrollRules).values({ id: `RULE-${crypto.randomUUID()}`, vendorId, ...values });
      await writeAudit(db, "rules_updated", "client", vendorId, "Updated client salary, statutory, overtime and attendance rules", actorEmail);
    } else if (action === "import-workbook") {
      runId = await importWorkbook(db, payload, actorEmail);
    } else if (action === "resolve-issues" || action === "recalculate") {
      await requireRun(db, runId, true);
      await recalculateRun(db, runId, action === "recalculate");
      await writeAudit(db, action === "recalculate" ? "recalculated" : "validation_checked", "payroll_run", runId, action === "recalculate" ? "Recalculated attendance, earnings, deductions and net pay" : "Rechecked employee payroll and bank readiness", actorEmail);
    } else if (action === "approve") {
      const run = await requireRun(db, runId, true);
      if (!run.employeeCount) throw new RequestError("Add employees before approving payroll", 409);
      if (run.issueCount > 0) throw new RequestError("Update the employee records that are still marked Review before approval", 409);
      if (run.grossEarnings <= 0) throw new RequestError("Add attendance or salary amounts before approving payroll", 409);
      if (run.netPayable < 0) throw new RequestError("Payroll net payable cannot be negative", 409);
      await db.update(payrollRuns).set({ status: "approved", approvedBy: user?.displayName ?? "Payroll approver", approvedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(eq(payrollRuns.id, runId));
      await writeAudit(db, "approved", "payroll_run", runId, "Approved payroll and unlocked payment exports", actorEmail);
    } else if (action === "reopen" || action === "reset-demo") {
      await requireRun(db, runId);
      await db.update(payrollRuns).set({ status: "draft", approvedBy: null, approvedAt: null, updatedAt: new Date().toISOString() }).where(eq(payrollRuns.id, runId));
      await recalculateRun(db, runId, false);
      await writeAudit(db, "reopened", "payroll_run", runId, "Reopened payroll for corrections; payment exports locked", actorEmail);
    } else if (action === "delete-payroll-run") {
      const run = await requireRun(db, runId, true);
      await db.delete(accommodationCharges).where(eq(accommodationCharges.runId, runId));
      await db.delete(payrollItems).where(eq(payrollItems.runId, runId));
      await db.delete(payrollRuns).where(eq(payrollRuns.id, runId));
      await writeAudit(db, "run_deleted", "payroll_run", runId, `Deleted ${run.payPeriod} payroll calculations; attendance records were preserved`, actorEmail);
    } else {
      throw new RequestError(`Unsupported action: ${action}`);
    }

    return Response.json({ ...await loadAppData(access), selectedRunId: runId });
  } catch (error) {
    const messages = errorMessages(error);
    const combined = messages.join(" ");
    if (/UNIQUE constraint failed: vendors\.code|vendors_code_(?:unique|key)/i.test(combined)) return Response.json({ error: "This client code already exists" }, { status: 409 });
    if (/UNIQUE constraint failed: shift_definitions\.vendor_id, shift_definitions\.name|shift_client_name_unique/i.test(combined)) return Response.json({ error: "This shift name already exists for the selected client" }, { status: 409 });
    if (/UNIQUE constraint failed: employees\.employee_code|employees_employee_code_(?:unique|key)/i.test(combined)) return Response.json({ error: "This employee code already exists" }, { status: 409 });
    const status = error instanceof RequestError ? error.status : 500;
    const message = error instanceof RequestError ? error.message : messages.at(-1) ?? "Unable to update payroll";
    if (status >= 500) console.error("Payroll application action failed", message.split("\n")[0]);
    return Response.json({ error: message }, { status });
  }
}
