ALTER TABLE `app_users` ADD `employee_code` text;
ALTER TABLE `app_users` ADD `department` text;
ALTER TABLE `app_users` ADD `date_of_joining` text;
ALTER TABLE `app_users` ADD `mobile_number` text;
ALTER TABLE `app_users` ADD `hostel_scope_json` text NOT NULL DEFAULT '[]';
ALTER TABLE `accommodation_rooms` ADD `rent_settings_json` text NOT NULL DEFAULT '{}';
ALTER TABLE `accommodation_rooms` ADD `rent_cutoff_day` integer NOT NULL DEFAULT 25;
ALTER TABLE `accommodation_rooms` ADD `late_join_rent_percent` real NOT NULL DEFAULT 50;
ALTER TABLE `accommodation_room_expenses` ADD `gas_cylinder_count` integer NOT NULL DEFAULT 0;
ALTER TABLE `accommodation_room_expenses` ADD `gas_payment_reference` text;
ALTER TABLE `accommodation_room_expenses` ADD `ration_payment_reference` text;
ALTER TABLE `accommodation_room_expenses` ADD `provision_payment_reference` text;
CREATE INDEX `accommodation_rooms_hostel_id_idx` ON `accommodation_rooms` (`hostel_id`);
ALTER TABLE `shift_definitions` ADD `client_unit_id` text REFERENCES `client_units`(`id`);
ALTER TABLE `shift_definitions` ADD `break_minutes` integer NOT NULL DEFAULT 0;
ALTER TABLE `shift_definitions` ADD `required_work_minutes` integer NOT NULL DEFAULT 480;
ALTER TABLE `shift_definitions` ADD `late_grace_minutes` integer NOT NULL DEFAULT 0;
ALTER TABLE `shift_definitions` ADD `late_deduction_minutes` integer NOT NULL DEFAULT 0;
ALTER TABLE `shift_definitions` ADD `early_grace_minutes` integer NOT NULL DEFAULT 0;
ALTER TABLE `shift_definitions` ADD `early_deduction_minutes` integer NOT NULL DEFAULT 0;
ALTER TABLE `shift_definitions` ADD `ot_mode` text NOT NULL DEFAULT 'approval';
ALTER TABLE `shift_definitions` ADD `fixed_ot_hours` real NOT NULL DEFAULT 0;
ALTER TABLE `attendance_entries` ADD `punch_in` text;
ALTER TABLE `attendance_entries` ADD `punch_out` text;
ALTER TABLE `attendance_entries` ADD `worked_hours` real NOT NULL DEFAULT 0;
ALTER TABLE `attendance_entries` ADD `deduction_hours` real NOT NULL DEFAULT 0;
CREATE INDEX `shift_definitions_client_unit_id_idx` ON `shift_definitions` (`client_unit_id`);
