begin;
insert into public.vendors(id,code,name,legal_name) values('CAPTURE-TEST-V','CAPTURE-TEST-CODE','Capture test','Capture test');
insert into public.client_units(id,vendor_id,client_name,unit_name,location) values('CAPTURE-TEST-U','CAPTURE-TEST-V','Capture test','Unit test','Test');
insert into public.shift_definitions(id,vendor_id,name,start_time,end_time,break_minutes,required_work_minutes) values('CAPTURE-TEST-S1','CAPTURE-TEST-V','General','09:00','18:00',60,480),('CAPTURE-TEST-S2','CAPTURE-TEST-V','Night','22:00','07:00',60,480);
insert into public.employees(id,vendor_id,client_unit_id,employee_code,name,department,date_of_joining,default_shift,shift_pattern,applicable_shifts_json) values('CAPTURE-TEST-E','CAPTURE-TEST-V','CAPTURE-TEST-U','CAPTURE-TEST-E','Capture test','Test','2026-09-01','General','rotational','["General","Night"]');
insert into public.payroll_runs(id,vendor_id,client_unit_id,pay_period,period_start,period_end) values('CAPTURE-TEST-R','CAPTURE-TEST-V','CAPTURE-TEST-U','2026-09','2026-09-12','2026-09-12');
insert into public.payroll_items(id,run_id,employee_id) values('CAPTURE-TEST-I','CAPTURE-TEST-R','CAPTURE-TEST-E');
insert into public.attendance_devices(id,client_unit_id,name,token_hash,created_by) values('00000000-0000-4000-8000-000000000010','CAPTURE-TEST-U','Test terminal',repeat('a',64),'test@example.invalid');
insert into public.attendance_device_mappings(id,device_id,device_user_id,employee_id,shift_code,created_by) values('CAPTURE-TEST-M','00000000-0000-4000-8000-000000000010','001','CAPTURE-TEST-E','General','test@example.invalid');
do $$
declare result jsonb;ids text[];saved text;blocked boolean;begin
 if has_table_privilege('anon','public.attendance_devices','SELECT') or has_table_privilege('authenticated','public.attendance_punches','INSERT') or has_function_privilege('authenticated','public.post_captured_attendance(text,text,text,text[],jsonb,text,text,text)','EXECUTE') then raise exception 'TEST failed: public permissions'; end if;
 select public.ingest_attendance_punches(jsonb_agg(jsonb_build_object('row_index',n,'id','CAPTURE-TEST-P'||n,'client_unit_id','CAPTURE-TEST-U','employee_id','CAPTURE-TEST-E','device_id','00000000-0000-4000-8000-000000000010','device_user_id','001','punched_at',at,'direction','in','source','biometric_api','event_key','CAPTURE-TEST-K'||n,'shift_code','General','created_by','test@example.invalid','created_at',now()::text))) into result from (values (1,'2026-09-12T03:30:00.000Z'),(2,'2026-09-12T03:31:00.000Z'),(3,'2026-09-12T12:30:00.000Z')) t(n,at);
 if (result->>'inserted')::int<>2 or (result->>'duplicates')::int<>1 then raise exception 'TEST failed: lock counts %',result; end if;
 if (select direction from public.attendance_punches where id='CAPTURE-TEST-P3')<>'out' then raise exception 'TEST failed: automatic OUT'; end if;
 blocked:=false;begin update public.payroll_runs set status='approved' where id='CAPTURE-TEST-R';exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'TEST failed: unconfirmed approval allowed';end if;
 select array_agg(id order by punched_at) into ids from public.attendance_punches where employee_id='CAPTURE-TEST-E';
 result:=public.post_captured_attendance('CAPTURE-TEST-U','CAPTURE-TEST-E','2026-09-12',ids,'{"statusCode":"P","shiftCode":"General","overtimeHours":0,"workedHours":8,"deductionHours":0,"punchIn":"09:00","punchOut":"18:00","remarks":"Test review"}'::jsonb,'test@example.invalid',null,'CAPTURE-TEST-APPROVAL');
 if (result->>'posted')::int<>2 then raise exception 'TEST failed: attendance posting'; end if;
 result:=public.confirm_payroll_attendance('CAPTURE-TEST-R','system','test@example.invalid','System records checked');
 insert into public.attendance_punches(id,client_unit_id,employee_id,punched_at,direction,source,event_key,shift_code,created_by) values('CAPTURE-TEST-LATE','CAPTURE-TEST-U','CAPTURE-TEST-E','2026-09-12T06:30:00.000Z','in','hr_correction','CAPTURE-TEST-LATE-K','General','test@example.invalid');
 if (select status from public.payroll_attendance_confirmations where run_id='CAPTURE-TEST-R')<>'pending' then raise exception 'TEST failed: later punch did not invalidate confirmation';end if;
 update public.attendance_punches set status='ignored' where id='CAPTURE-TEST-LATE';
 result:=public.confirm_payroll_attendance('CAPTURE-TEST-R','system','test@example.invalid','Late duplicate reviewed');
 blocked:=false;begin perform public.confirm_payroll_attendance('CAPTURE-TEST-R','client_attendance','test@example.invalid','Incomplete client file');exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'TEST failed: incomplete client attendance confirmed';end if;
 insert into public.client_attendance_records(id,run_id,employee_id,attendance_date,status_code,shift_code,overtime_hours,updated_at) values('CAPTURE-TEST-C','CAPTURE-TEST-R','CAPTURE-TEST-E','2026-09-12','HD','General',1,now()::text);
 insert into public.client_attendance_records(id,run_id,employee_id,attendance_date,status_code,shift_code,overtime_hours,updated_at) values('CAPTURE-TEST-OUTSIDE','CAPTURE-TEST-R','CAPTURE-TEST-E','2026-09-11','P','General',8,now()::text);
 result:=public.payroll_attendance_review('CAPTURE-TEST-R');
 if (result->'employees'->0->>'system_days')::numeric<>1 or (result->'employees'->0->>'client_days')::numeric<>.5 then raise exception 'TEST failed: separate client/system records %',result;end if;
 result:=public.confirm_payroll_attendance('CAPTURE-TEST-R','client_attendance','test@example.invalid','Client attendance reconciled');
 update public.client_attendance_records set overtime_hours=2 where id='CAPTURE-TEST-C';
 if (select status from public.payroll_attendance_confirmations where run_id='CAPTURE-TEST-R')<>'pending' then raise exception 'TEST failed: changes did not invalidate confirmation';end if;
 result:=public.confirm_payroll_attendance('CAPTURE-TEST-R','client_attendance','test@example.invalid','Client adjustment reviewed');
 update public.payroll_runs set status='approved' where id='CAPTURE-TEST-R';
 blocked:=false;begin perform public.post_captured_attendance('CAPTURE-TEST-U','CAPTURE-TEST-E','2026-09-12',ids,'{"statusCode":"P","shiftCode":"General","overtimeHours":0,"workedHours":8}'::jsonb,'test@example.invalid',null,'CAPTURE-TEST-LOCK');exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'TEST failed: approved payroll changed';end if;
 update public.payroll_runs set status='draft' where id='CAPTURE-TEST-R';
 insert into public.payment_export_batches(id,run_id,status,locked_by,locked_at,employee_count) values('CAPTURE-TEST-B','CAPTURE-TEST-R','downloaded','test@example.invalid',now()::text,1);
 blocked:=false;begin perform public.confirm_payroll_attendance('CAPTURE-TEST-R','system','test@example.invalid','Paid payroll check');exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'TEST failed: paid payroll source changed';end if;
 -- Night assignment and ten-minute boundary use a separate employee outside the reviewed run.
 insert into public.employees(id,vendor_id,client_unit_id,employee_code,name,department,date_of_joining,default_shift,shift_pattern,applicable_shifts_json) values('CAPTURE-TEST-E2','CAPTURE-TEST-V','CAPTURE-TEST-U','CAPTURE-TEST-E2','Night test','Test','2026-09-01','General','rotational','["General","Night"]');
 insert into public.attendance_punches(id,client_unit_id,employee_id,punched_at,direction,source,event_key,shift_code,created_by) values('CAPTURE-TEST-N1','CAPTURE-TEST-U','CAPTURE-TEST-E2','2026-09-12T16:28:00.000Z','in','qr','CAPTURE-TEST-NK1','General','test@example.invalid');
 if (select shift_code from public.attendance_punches where id='CAPTURE-TEST-N1')<>'Night' then raise exception 'TEST failed: nearest rotational shift';end if;
 insert into public.attendance_punches(id,client_unit_id,employee_id,punched_at,direction,source,event_key,shift_code,created_by) values('CAPTURE-TEST-N2','CAPTURE-TEST-U','CAPTURE-TEST-E2','2026-09-12T16:38:00.000Z','in','qr','CAPTURE-TEST-NK2','General','test@example.invalid');
 if (select direction from public.attendance_punches where id='CAPTURE-TEST-N2')<>'out' then raise exception 'TEST failed: ten-minute boundary';end if;
 insert into public.attendance_punches(id,client_unit_id,employee_id,punched_at,direction,source,event_key,shift_code,created_by) values('CAPTURE-TEST-N3','CAPTURE-TEST-U','CAPTURE-TEST-E2','2026-09-12T16:39:00.000Z','in','qr','CAPTURE-TEST-NK3','General','test@example.invalid');
 if exists(select 1 from public.attendance_punches where id='CAPTURE-TEST-N3') then raise exception 'TEST failed: repeated OUT became new IN';end if;
end $$;
rollback;
select 'All attendance database assertions passed; test records rolled back' as result;
