"use client";
import { useState, type FormEvent } from "react";
import type { AccommodationRoom, AccommodationType, Employee, Hostel, HostelUtilityReading, RoomExpense } from "./payroll-app";
type Action = (action: string, message: string, details?: Record<string, unknown>) => Promise<boolean>;
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(value);

export function HostelMaster({ vendorId, types, hostels, rooms, employees, readings, expenses, payPeriod, canManage, canApprove, isActing, onAction }: { vendorId: string; types: AccommodationType[]; hostels: Hostel[]; rooms: AccommodationRoom[]; employees: Employee[]; readings: HostelUtilityReading[]; expenses: RoomExpense[]; payPeriod: string; canManage: boolean; canApprove: boolean; isActing: boolean; onAction: Action }) {
  const activeTypes = types.filter((type) => type.vendorId === vendorId && type.status === "active");
  const [typeId, setTypeId] = useState(activeTypes[0]?.id ?? "");
  const typeHostels = hostels.filter((hostel) => hostel.vendorId === vendorId && hostel.accommodationTypeId === typeId);
  const [hostelId, setHostelId] = useState("");
  const selected = typeHostels.find((hostel) => hostel.id === hostelId) ?? typeHostels[0];
  const [utilityType, setUtilityType] = useState<"eb" | "water_purchase">("eb");
  const [readingDate, setReadingDate] = useState(new Date().toISOString().slice(0, 10));
  const eligibleRooms = rooms.filter((room) => room.vendorId === vendorId && room.accommodationTypeId === typeId);
  const hostelRooms = eligibleRooms.filter((room) => room.hostelId === selected?.id);
  const periodExpenses = expenses.filter((expense) => expense.payPeriod === payPeriod && hostelRooms.some((room) => room.id === expense.roomId));
  const totals = periodExpenses.reduce((sum, expense) => ({ gas: sum.gas + expense.gasAmount, ration: sum.ration + expense.rationAmount, provision: sum.provision + expense.provisionAmount }), { gas: 0, ration: 0, provision: 0 });
  const selectedReadings = readings.filter((reading) => reading.hostelId === selected?.id).sort((a, b) => b.readingDate.localeCompare(a.readingDate));

  async function createHostel(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const ok = await onAction("save-hostel", "Hostel created under the selected accommodation type", { vendorId, accommodationTypeId: typeId, name: form.get("name"), address: form.get("address"), inchargeName: form.get("inchargeName"), ebMeterNumber: form.get("ebMeterNumber"), remarks: form.get("remarks") }); if (ok) event.currentTarget.reset(); }
  async function saveUtility(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); const ok = await onAction("save-hostel-utility", utilityType === "eb" ? "Daily hostel EB reading saved" : "Daily hostel water update saved", { hostelId: selected.id, utilityType, readingDate, readingValue: form.get("readingValue"), tankerQuantity: form.get("quantity"), amount: form.get("amount"), remarks: form.get("remarks") }); if (ok) event.currentTarget.reset(); }

  return <div className="section-stack">
    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Step 1 · Accommodation type</span><h2>Select type before creating a hostel</h2></div></div><div className="accommodation-type-grid">{activeTypes.map((type) => <button type="button" key={type.id} className={`accommodation-card accommodation-filter-card ${typeId === type.id ? "accommodation-filter-selected" : ""}`} onClick={() => setTypeId(type.id)}><span className="accommodation-icon">{type.name.slice(0, 1).toUpperCase()}</span><div><span>{type.name}</span><strong>{hostels.filter((hostel) => hostel.accommodationTypeId === type.id).length} hostels</strong><small>{rooms.filter((room) => room.accommodationTypeId === type.id).length} rooms</small></div></button>)}</div>{!activeTypes.length ? <div className="enhancement-empty">Create an accommodation type first under Operational Masters.</div> : null}</section>
    {typeId ? <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Step 2 · Hostel master</span><h2>Create and select a hostel under {activeTypes.find((type) => type.id === typeId)?.name}</h2></div><label><span>Selected hostel</span><select value={selected?.id ?? ""} onChange={(event) => setHostelId(event.target.value)}><option value="">Choose hostel</option>{typeHostels.map((hostel) => <option value={hostel.id} key={hostel.id}>{hostel.name}</option>)}</select></label></div>{canManage ? <form className="form-grid" onSubmit={createHostel}><label><span>Hostel name *</span><input name="name" placeholder="Joy Hostel - Madhapur" required /></label><label><span>Address / location</span><input name="address" /></label><label><span>Hostel in-charge</span><input name="inchargeName" /></label><label><span>EB meter number</span><input name="ebMeterNumber" /></label><label className="form-span"><span>Remarks</span><input name="remarks" /></label><button className="primary-button form-span" disabled={isActing}>Create hostel under selected type</button></form> : null}</section> : null}
    {selected ? <><section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">Step 3 · Room mapping</span><h2>{selected.name}: map {activeTypes.find((type) => type.id === typeId)?.name} rooms</h2></div><span className="muted-label">{hostelRooms.length} mapped rooms · {employees.filter((employee) => hostelRooms.some((room) => room.id === employee.roomId) && employee.status === "active").length} residents</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Room</th><th>Capacity</th><th>Active residents</th><th>Mapped hostel</th></tr></thead><tbody>{eligibleRooms.map((room) => <tr key={room.id}><td><strong>{room.roomNumber}</strong><small>{room.address ?? "—"}</small></td><td>{room.capacity || "Unlimited"}</td><td>{employees.filter((employee) => employee.roomId === room.id && employee.status === "active").length}</td><td>{canManage ? <select value={room.hostelId ?? ""} onChange={(event) => event.target.value && void onAction("assign-room-hostel", "Room mapped under hostel", { roomId: room.id, hostelId: event.target.value })}><option value="">Not mapped</option>{typeHostels.map((hostel) => <option value={hostel.id} key={hostel.id}>{hostel.name}</option>)}</select> : typeHostels.find((hostel) => hostel.id === room.hostelId)?.name ?? "Not mapped"}</td></tr>)}</tbody></table></div>{!eligibleRooms.length ? <div className="enhancement-empty">Create rooms under this accommodation type in Accommodation, then return here to map them.</div> : null}</section>
    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Daily hostel utilities</span><h2>{selected.name}: separate EB and water tracking</h2></div><span className="muted-label">Every entry is hostel-specific and date-wise</span></div>{canManage ? <form className="form-grid" onSubmit={saveUtility}><label><span>Daily update type</span><select value={utilityType} onChange={(event) => setUtilityType(event.target.value as "eb" | "water_purchase")}><option value="eb">EB meter reading</option><option value="water_purchase">Water update / purchase</option></select></label><label><span>Date *</span><input type="date" value={readingDate} onChange={(event) => setReadingDate(event.target.value)} required /></label>{utilityType === "eb" ? <label><span>Current EB reading *</span><input name="readingValue" type="number" min="0" step="0.01" required /></label> : <label><span>Water quantity (litres) *</span><input name="quantity" type="number" min="0" step="0.01" required /></label>}<label><span>Amount (₹)</span><input name="amount" type="number" min="0" step="0.01" /></label><label className="form-span"><span>Remarks / supplier</span><input name="remarks" /></label><button className="primary-button form-span" disabled={isActing}>Save daily hostel update</button></form> : null}<div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Hostel</th><th>Utility</th><th>Reading / quantity</th><th>Daily consumption</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{selectedReadings.map((reading) => <tr key={reading.id}><td>{reading.readingDate}</td><td>{selected.name}</td><td>{reading.utilityType === "eb" ? "EB" : "Water"}</td><td>{reading.utilityType === "eb" ? reading.readingValue : `${reading.tankerQuantity} L`}</td><td>{reading.utilityType === "eb" ? reading.consumption : "—"}</td><td>{money(reading.amount)}</td><td>{reading.status}</td><td>{reading.status === "draft" && canApprove ? <button className="record-action" disabled={isActing} onClick={() => void onAction("approve-hostel-utility", "Hostel utility update approved", { id: reading.id })}>Approve</button> : null}</td></tr>)}</tbody></table></div>{!selectedReadings.length ? <div className="enhancement-empty">No daily EB or water entries for this hostel yet.</div> : null}</section>
    <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">Room deductions · {payPeriod}</span><h2>{selected.name}: cumulative Gas, Ration and Provision</h2></div><strong>{money(totals.gas + totals.ration + totals.provision)}</strong></div><div className="payment-summary-grid"><article><div><small>Gas cylinders</small><strong>{money(totals.gas)}</strong></div></article><article><div><small>Ration</small><strong>{money(totals.ration)}</strong></div></article><article><div><small>Provision</small><strong>{money(totals.provision)}</strong></div></article></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Room</th><th>Gas</th><th>Ration</th><th>Provision</th><th>Roommates</th><th>Salary status</th></tr></thead><tbody>{hostelRooms.map((room) => { const expense = periodExpenses.find((entry) => entry.roomId === room.id); return <tr key={room.id}><td>{room.roomNumber}</td><td>{expense?.gasDate ?? "—"}<small>{money(expense?.gasAmount ?? 0)}</small></td><td>{expense?.rationDate ?? "—"}<small>{money(expense?.rationAmount ?? 0)}</small></td><td>{expense?.provisionDate ?? "—"}<small>{money(expense?.provisionAmount ?? 0)}</small></td><td>{expense?.occupantCount || employees.filter((employee) => employee.roomId === room.id && employee.status === "active").length}</td><td>{expense?.status ?? "Not entered"}</td></tr>; })}</tbody></table></div><small className="muted-label">Enter and finalize room expenses in Accommodation. This hostel summary rolls up only its mapped rooms.</small></section></> : null}
  </div>;
}
