"use client";
import { useMemo, useState, type FormEvent } from "react";
import type { AppData } from "./payroll-app";

const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
const today = () => new Date().toISOString().slice(0, 10);
const dueDays = (date: string | null) => date ? Math.ceil((new Date(`${date}T00:00:00`).getTime() - Date.now()) / 86400000) : null;

export function OperationsView({ data, canManage, canApprove, isActing, onAction }: { data: AppData; canManage: boolean; canApprove: boolean; isActing: boolean; onAction: (action: string, message: string, details?: Record<string, unknown>) => Promise<boolean> }) {
  const [tab, setTab] = useState<"vehicles" | "eb">("vehicles");
  const [vehicleId, setVehicleId] = useState(data.vehicles[0]?.id ?? "");
  const [meterId, setMeterId] = useState(data.utilityMeters[0]?.id ?? "");
  const [reportMode, setReportMode] = useState<"month" | "year" | "all">("month");
  const [reportPeriod, setReportPeriod] = useState(today().slice(0, 7));
  const records = data.vehicleRecords.filter((item) => (!vehicleId || item.vehicleId === vehicleId) && (reportMode === "all" || item.recordDate.startsWith(reportMode === "year" ? reportPeriod.slice(0, 4) : reportPeriod)));
  const totals = useMemo(() => ({ km: records.reduce((sum, item) => sum + Math.max(0, (item.endKm ?? 0) - (item.startKm ?? 0)), 0), litres: records.reduce((sum, item) => sum + item.litres, 0), expense: records.reduce((sum, item) => sum + item.amount, 0) }), [records]);
  async function submit(action: string, message: string, event: FormEvent<HTMLFormElement>) { event.preventDefault(); await onAction(action, message, Object.fromEntries(new FormData(event.currentTarget))); }
  const reminders = data.vehicles.flatMap((vehicle) => [["Permit", vehicle.permitExpiry], ["Insurance", vehicle.insuranceExpiry], ["FC", vehicle.fcExpiry], ["Pollution", vehicle.pollutionExpiry], ["Service", vehicle.nextServiceDate]].map(([label, date]) => ({ vehicle, label, date, days: dueDays(date) })).filter((item) => item.date && (item.days ?? 999) <= 90)).sort((a,b)=>(a.days??0)-(b.days??0));
  return <div className="section-stack operations-view"><div className="table-toolbar"><div className="filter-tabs"><button className={tab === "vehicles" ? "filter-active" : ""} onClick={() => setTab("vehicles")}>Vehicle tracker</button><button className={tab === "eb" ? "filter-active" : ""} onClick={() => setTab("eb")}>Hostel & office EB</button></div>{tab === "vehicles" ? <div className="attendance-toolbar"><select aria-label="Expense tracker period" value={reportMode} onChange={(event)=>setReportMode(event.target.value as "month"|"year"|"all")}><option value="month">Month wise</option><option value="year">Annual</option><option value="all">All records</option></select>{reportMode !== "all" ? <input aria-label="Tracker month" type="month" value={reportPeriod} onChange={(event)=>setReportPeriod(event.target.value)} /> : null}</div> : null}</div>
    {tab === "vehicles" ? <><section className="kpi-grid attendance-kpis"><article className="metric-card"><small>Total vehicles</small><strong>{data.vehicles.length}</strong></article><article className="metric-card"><small>Tracked kilometres</small><strong>{totals.km.toFixed(0)} km</strong></article><article className="metric-card"><small>Fuel / mileage</small><strong>{totals.litres ? `${(totals.km / totals.litres).toFixed(2)} km/L` : "—"}</strong></article><article className="metric-card"><small>Selected expenses</small><strong>{money(totals.expense)}</strong></article><article className="metric-card"><small>Due within 3 months</small><strong>{reminders.length}</strong></article></section>
      {canManage ? <form className="panel form-grid" onSubmit={(event) => void submit("save-vehicle", "Vehicle saved", event)}><h2 className="form-span">Add company vehicle</h2><label><span>Joy company</span><select name="vendorId">{data.vendors.map((v)=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label><span>Registration number</span><input name="registrationNumber" required /></label><label><span>Vehicle name</span><input name="vehicleName" required /></label><label><span>Type</span><input name="vehicleType" placeholder="Car / van / bike" /></label><label><span>Current odometer</span><input name="currentOdometer" type="number" min="0" /></label>{[["permitExpiry","Permit expiry"],["insuranceExpiry","Insurance expiry"],["fcExpiry","FC expiry"],["pollutionExpiry","Pollution expiry"],["nextServiceDate","Next service date"],["tyreChangedDate","Tyre changed date"],["lastWaterWashDate","Last water wash"],["lastWheelAlignmentDate","Last wheel alignment"]].map(([name,label])=><label key={name}><span>{label}</span><input name={name} type="date" /></label>)}<label><span>Next service km</span><input name="nextServiceKm" type="number" min="0" /></label><label><span>Tyre changed km</span><input name="tyreChangedKm" type="number" min="0" /></label><button className="primary-button form-span" disabled={isActing}>Save vehicle</button></form> : null}
      <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">90-day compliance reminders</span><h2>Permit, insurance, FC, pollution & service</h2></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Vehicle</th><th>Reminder</th><th>Due date</th><th>Days</th></tr></thead><tbody>{reminders.map((item)=><tr key={`${item.vehicle.id}-${item.label}`}><td>{item.vehicle.registrationNumber}<small>{item.vehicle.vehicleName}</small></td><td>{item.label}</td><td>{item.date}</td><td className={(item.days??0)<0 ? "pending-text" : ""}>{(item.days??0)<0 ? `${Math.abs(item.days??0)} overdue` : item.days}</td></tr>)}</tbody></table></div></section>
      {canManage && data.vehicles.length ? <div className="vehicle-entry-grid"><form className="panel form-grid" onSubmit={(event) => void submit("save-vehicle-record", "Daily vehicle KM movement recorded", event)}><h2 className="form-span">Daily KM & trip movement</h2><input type="hidden" name="recordType" value="trip" /><label><span>Vehicle</span><select name="vehicleId" value={vehicleId} onChange={(e)=>setVehicleId(e.target.value)}>{data.vehicles.map((v)=><option value={v.id} key={v.id}>{v.registrationNumber} · {v.vehicleName}</option>)}</select></label><label><span>Date</span><input name="recordDate" type="date" defaultValue={today()} required /></label><label><span>Starting KM *</span><input name="startKm" type="number" required /></label><label><span>Ending KM *</span><input name="endKm" type="number" required /></label><label><span>Trip from</span><input name="tripFrom" /></label><label><span>Trip to</span><input name="tripTo" /></label><label className="form-span"><span>Purpose / movement details</span><input name="purpose" /></label><button className="primary-button form-span" disabled={isActing}>Save KM movement</button></form><form className="panel form-grid" onSubmit={(event) => void submit("save-vehicle-record", "Date-wise vehicle expense recorded", event)}><h2 className="form-span">Date-wise vehicle expense</h2><label><span>Vehicle</span><select name="vehicleId" value={vehicleId} onChange={(e)=>setVehicleId(e.target.value)}>{data.vehicles.map((v)=><option value={v.id} key={v.id}>{v.registrationNumber} · {v.vehicleName}</option>)}</select></label><label><span>Expense date</span><input name="recordDate" type="date" defaultValue={today()} required /></label><label><span>Expense type *</span><select name="recordType">{["fuel","service","tyre","water_wash","wheel_alignment","permit","insurance","fc","pollution","other"].map(v=><option value={v} key={v}>{v.replaceAll("_"," ")}</option>)}</select></label><label><span>Amount (₹) *</span><input name="amount" type="number" min="0.01" step="0.01" required /></label><label><span>Odometer at expense</span><input name="startKm" type="number" /></label><label><span>Fuel litres (fuel only)</span><input name="litres" type="number" step="0.01" /></label><label><span>Next due date</span><input name="nextDueDate" type="date" /></label><label><span>Next due KM</span><input name="nextDueKm" type="number" /></label><label className="form-span"><span>Vendor / bill / remarks</span><input name="remarks" /></label><button className="primary-button form-span" disabled={isActing}>Save expense</button></form></div> : null}
      <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">Monthly & annual-ready register</span><h2>Trips, kilometres, fuel and all expenses</h2></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Vehicle</th><th>Type / trip</th><th>KM</th><th>Fuel</th><th>Expense</th><th>Status</th><th>Approval</th></tr></thead><tbody>{records.map((record)=><tr key={record.id}><td>{record.recordDate}</td><td>{data.vehicles.find(v=>v.id===record.vehicleId)?.registrationNumber}</td><td>{record.recordType}<small>{record.tripFrom && record.tripTo ? `${record.tripFrom} → ${record.tripTo}` : record.purpose}</small></td><td>{Math.max(0,(record.endKm??0)-(record.startKm??0))}</td><td>{record.litres}</td><td>{money(record.amount)}</td><td>{record.status}</td><td>{record.status === "draft" && canApprove ? <button className="record-action" onClick={()=>void onAction("approve-operation-record","Vehicle record approved",{recordType:"vehicle",id:record.id})}>Approve</button> : "—"}</td></tr>)}</tbody></table></div></section></> : <>
      {canManage ? <form className="panel form-grid" onSubmit={(event)=>void submit("save-utility-meter","EB meter saved",event)}><h2 className="form-span">Add hostel / office EB meter</h2><label><span>Joy company</span><select name="vendorId">{data.vendors.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label><span>Location type</span><select name="locationType"><option value="hostel">Hostel</option><option value="office">Office</option></select></label><label><span>Location name</span><input name="locationName" required /></label><label><span>Meter number</span><input name="meterNumber" /></label><button className="primary-button form-span">Save EB meter</button></form> : null}
      {canManage && data.utilityMeters.length ? <form className="panel form-grid" onSubmit={(event)=>void submit("save-eb-reading","Daily EB reading saved",event)}><h2 className="form-span">Daily EB reading</h2><label><span>Meter / location</span><select name="meterId" value={meterId} onChange={e=>setMeterId(e.target.value)}>{data.utilityMeters.map(m=><option value={m.id} key={m.id}>{m.locationName} · {m.meterNumber}</option>)}</select></label><label><span>Date</span><input name="readingDate" type="date" defaultValue={today()} required /></label><label><span>Meter reading</span><input name="readingValue" type="number" min="0" step="0.01" required /></label><label><span>Bill / expense amount</span><input name="amount" type="number" min="0" step="0.01" /></label><label className="form-span"><span>Remarks</span><input name="remarks" /></label><button className="primary-button form-span">Save draft for approval</button></form> : null}
      <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">Hostel & office monitoring</span><h2>Daily EB consumption register</h2></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Location</th><th>Reading</th><th>Daily units</th><th>Amount</th><th>Status</th><th>Approval</th></tr></thead><tbody>{data.ebReadings.map(r=><tr key={r.id}><td>{r.readingDate}</td><td>{data.utilityMeters.find(m=>m.id===r.meterId)?.locationName}</td><td>{r.readingValue}</td><td>{r.unitsConsumed}</td><td>{money(r.amount)}</td><td>{r.status}</td><td>{r.status === "draft" && canApprove ? <button className="record-action" onClick={()=>void onAction("approve-operation-record","EB reading approved",{recordType:"eb",id:r.id})}>Approve</button> : "—"}</td></tr>)}</tbody></table></div></section></>}
  </div>;
}
