"use client";

import { useMemo, useState, type FormEvent } from "react";
import type {
  AccommodationCharge,
  AppData,
  ClientUnit,
  Employee,
  PayrollItem,
  PayrollRun,
  RecoveryEntry,
  Vendor,
} from "./payroll-app";

type ReportRow = Array<string | number>;

function csvCell(value: string | number) { return `"${String(value).replaceAll('"', '""')}"`; }
function save(filename: string, body: BlobPart, type: string) { const url=URL.createObjectURL(new Blob([body],{type})); const link=document.createElement("a"); link.href=url; link.download=filename; link.click(); URL.revokeObjectURL(url); }
function exportCsv(name:string,rows:ReportRow[]){save(`${name}.csv`,rows.map(row=>row.map(csvCell).join(",")).join("\n"),"text/csv;charset=utf-8");}
function exportExcel(name:string,rows:ReportRow[]){const table=`<table>${rows.map((row,index)=>`<tr>${row.map(value=>`<${index?"td":"th"}>${String(value).replaceAll("&","&amp;").replaceAll("<","&lt;")}</${index?"td":"th"}>`).join("")}</tr>`).join("")}</table>`;save(`${name}.xls`,`\ufeff<html><head><meta charset="utf-8"></head><body>${table}</body></html>`,"application/vnd.ms-excel");}

const recoveryLabels:Record<string,string>={rent:"Room rent",bus:"Bus",food:"Food",advance:"Salary advance",idCard:"ID card",medical:"Medical",ticket:"Ticket",shoe:"Shoe",aadhaarUpdate:"Aadhaar update",bankAccountCharge:"Bank account charge",tshirt:"T-shirt",oldPending:"Old pending",returnAmount:"Return amount"};
function voucherBrand(vendor?:Vendor,unit?:ClientUnit){const companyName=vendor?.legalName??vendor?.name??"JOY GROUPS";const corporate=companyName.toLowerCase().includes("corporate");return{companyName,clientEmployer:unit?`${unit.clientName}${unit.unitName?` · ${unit.unitName}`:""}`:"Client employer",address:"8/40, 16 Krishna Complex, Thennampalayam, Arasur, Coimbatore - 641407",email:corporate?"info@joycorporatesolutions.com":"operations@joyindia.in",contact:"+91 90807 76580"};}

export function RecoveryCenter({run,employees,items,charges,data,canManage,canApprove,isActing,onAction}:{run:PayrollRun|null;employees:Employee[];items:PayrollItem[];charges:AccommodationCharge[];data:AppData;canManage:boolean;canApprove:boolean;isActing:boolean;onAction:(action:string,message:string,details?:Record<string,unknown>)=>Promise<boolean>;}){
 const [employeeId,setEmployeeId]=useState(employees[0]?.id??""); const [recoveryDate,setRecoveryDate]=useState(run?.periodStart??`${run?.payPeriod??new Date().toISOString().slice(0,7)}-01`); const [recoveryType,setRecoveryType]=useState("advance"); const [amount,setAmount]=useState(0); const [reference,setReference]=useState(""); const [notes,setNotes]=useState(""); const [voucherEmployeeId,setVoucherEmployeeId]=useState<string|null>(null); const [bulkVouchers,setBulkVouchers]=useState(false);
 const runCharges=run?charges.filter(c=>c.runId===run.id):[]; const entries=run?data.recoveryEntries.filter(e=>e.runId===run.id):[]; const finalizations=run?data.recoveryFinalizations.filter(e=>e.runId===run.id):[];
 const employeeRows=employees.map(employee=>{const charge=runCharges.find(e=>e.employeeId===employee.id);const item=items.find(e=>e.employeeId===employee.id);const individual=charge?charge.rent+charge.bus+charge.food+charge.advance+charge.idCard+charge.medical+charge.ticket+charge.shoe+charge.aadhaarUpdate+charge.bankAccountCharge+charge.tshirt+charge.oldPending:0;const shared=charge?charge.gasShare+charge.rationShare+charge.provisionShare:0;const dated=entries.filter(e=>e.employeeId===employee.id);return{employee,charge,individual,shared,total:individual+shared,item,dated};}).filter(row=>Boolean(row.item)||Boolean(row.charge)||row.dated.length>0||row.shared>0);
 const roomRows=data.roomExpenses.filter(expense=>!run||expense.payPeriod===run.payPeriod).map(expense=>({expense,room:data.accommodationRooms.find(room=>room.id===expense.roomId)}));
 async function addRecovery(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!run)return;const ok=await onAction("save-recovery-entry","Date-wise recovery added",{employeeId,recoveryDate,recoveryType,amount,reference,notes});if(ok){setAmount(0);setReference("");setNotes("");}}
 return <div className="section-stack">
 {canManage&&run?<form className="panel form-grid" onSubmit={event=>void addRecovery(event)}><div className="panel-heading form-span"><div><span className="eyebrow">Salary-cycle recovery entry</span><h2>Add recovery by date</h2></div></div><label><span>Employee *</span><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeCode} · {e.name}</option>)}</select></label><label><span>Recovery date *</span><input type="date" value={recoveryDate} onChange={e=>setRecoveryDate(e.target.value)}/></label><label><span>Recovery type *</span><select value={recoveryType} onChange={e=>setRecoveryType(e.target.value)}>{Object.entries(recoveryLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Amount (₹) *</span><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label><span>Reference / voucher no.</span><input value={reference} onChange={e=>setReference(e.target.value)}/></label><label><span>Remarks</span><input value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary-button form-span" disabled={isActing||!employeeId||amount<=0}>Add dated recovery</button></form>:null}
 <section className="panel recovery-final-payable-panel"><div className="panel-heading"><div><span className="eyebrow">Recovery totals by applicable employee</span><h2>Net salary → recoveries → final payable</h2></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Employee</th><th>Employer unit</th><th>Room</th><th>Net before recovery</th><th>Rent</th><th>Bus</th><th>Food</th><th>Advance</th><th>ID</th><th>Medical</th><th>Ticket</th><th>Shoe</th><th>Aadhaar</th><th>Bank A/c</th><th>T-shirt</th><th>Old pending</th><th>Gas</th><th>Ration</th><th>Provision</th><th>Total recovery</th><th>Return</th><th>Final payable</th></tr></thead><tbody>{employeeRows.map(({employee,charge,item,total},index)=>{const net=Number(item?.netPayable??0);const ret=Number(charge?.returnAmount??0);return <tr key={employee.id}><td>{index+1}</td><td><strong>{employee.name}</strong><small>{employee.employeeCode}</small></td><td>{employee.unitName??employee.clientName??"—"}</td><td>{employee.roomNumber??"—"}</td><td>₹{net.toFixed(2)}</td><td>₹{Number(charge?.rent??0).toFixed(2)}</td><td>₹{Number(charge?.bus??0).toFixed(2)}</td><td>₹{Number(charge?.food??0).toFixed(2)}</td><td>₹{Number(charge?.advance??0).toFixed(2)}</td><td>₹{Number(charge?.idCard??0).toFixed(2)}</td><td>₹{Number(charge?.medical??0).toFixed(2)}</td><td>₹{Number(charge?.ticket??0).toFixed(2)}</td><td>₹{Number(charge?.shoe??0).toFixed(2)}</td><td>₹{Number(charge?.aadhaarUpdate??0).toFixed(2)}</td><td>₹{Number(charge?.bankAccountCharge??0).toFixed(2)}</td><td>₹{Number(charge?.tshirt??0).toFixed(2)}</td><td>₹{Number(charge?.oldPending??0).toFixed(2)}</td><td>₹{Number(charge?.gasShare??0).toFixed(2)}</td><td>₹{Number(charge?.rationShare??0).toFixed(2)}</td><td>₹{Number(charge?.provisionShare??0).toFixed(2)}</td><td><strong>₹{total.toFixed(2)}</strong></td><td>₹{ret.toFixed(2)}</td><td><strong>₹{Math.max(0,net-total+ret).toFixed(2)}</strong></td></tr>})}</tbody></table></div>{employeeRows.length===0?<div className="empty-state">No payroll employees are available for this run.</div>:null}</section>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Shared room recoveries</span><h2>Gas, Ration & Provision split</h2></div><span className="muted-label">Finalized total ÷ room occupant count</span></div><div className="table-wrap"><table><thead><tr><th>Room</th><th>Month</th><th>Occupants</th><th>Gas</th><th>Ration</th><th>Provision</th></tr></thead><tbody>{roomRows.map(({expense,room})=><tr key={expense.id}><td><strong>{room?.roomNumber??"—"}</strong></td><td>{expense.payPeriod}</td><td>{expense.occupantCount}</td><td>₹{expense.gasAmount.toFixed(2)}</td><td>₹{expense.rationAmount.toFixed(2)}</td><td>₹{expense.provisionAmount.toFixed(2)}</td></tr>)}</tbody></table></div></section>
 </div>;
}
