begin;
alter table public.app_users add column if not exists employee_code text;
alter table public.app_users add column if not exists department text;
alter table public.app_users add column if not exists date_of_joining text;
alter table public.app_users add column if not exists mobile_number text;
alter table public.app_users add column if not exists hostel_scope_json text not null default '[]';
alter table public.accommodation_rooms add column if not exists rent_settings_json text not null default '{}';
alter table public.accommodation_rooms add column if not exists rent_cutoff_day integer not null default 25;
alter table public.accommodation_rooms add column if not exists late_join_rent_percent double precision not null default 50;
alter table public.accommodation_room_expenses add column if not exists gas_cylinder_count integer not null default 0;
alter table public.accommodation_room_expenses add column if not exists gas_payment_reference text;
alter table public.accommodation_room_expenses add column if not exists ration_payment_reference text;
alter table public.accommodation_room_expenses add column if not exists provision_payment_reference text;
create index if not exists accommodation_rooms_hostel_id_idx on public.accommodation_rooms(hostel_id);
alter table public.shift_definitions add column if not exists client_unit_id text references public.client_units(id);
alter table public.shift_definitions add column if not exists break_minutes integer not null default 0;
alter table public.shift_definitions add column if not exists required_work_minutes integer not null default 480;
alter table public.shift_definitions add column if not exists late_grace_minutes integer not null default 0;
alter table public.shift_definitions add column if not exists late_deduction_minutes integer not null default 0;
alter table public.shift_definitions add column if not exists early_grace_minutes integer not null default 0;
alter table public.shift_definitions add column if not exists early_deduction_minutes integer not null default 0;
alter table public.shift_definitions add column if not exists ot_mode text not null default 'approval';
alter table public.shift_definitions add column if not exists fixed_ot_hours double precision not null default 0;
alter table public.attendance_entries add column if not exists punch_in text;
alter table public.attendance_entries add column if not exists punch_out text;
alter table public.attendance_entries add column if not exists worked_hours double precision not null default 0;
alter table public.attendance_entries add column if not exists deduction_hours double precision not null default 0;
create index if not exists shift_definitions_client_unit_id_idx on public.shift_definitions(client_unit_id);
commit;
