-- Joy Client Payroll Manager: Supabase PostgreSQL production schema.
-- Run this complete migration in Supabase SQL Editor before deploying the API.
-- Employee and salary tables are intentionally inaccessible through the browser
-- Data API: the authenticated payroll Edge Function enforces module permissions.

begin;

create table if not exists public.app_users (
  id text primary key,
  email text not null unique,
  full_name text,
  role text not null default 'hr_team'
    check (role in ('super_admin', 'payroll_team', 'hr_team')),
  status text not null default 'active' check (status in ('active', 'inactive')),
  permissions_json text not null,
  can_approve_payroll integer not null default 0 check (can_approve_payroll in (0, 1)),
  created_by text,
  created_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  updated_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  last_login_at text
);

create table if not exists public.vendors (
  id text primary key,
  code text not null unique,
  name text not null,
  legal_name text not null,
  epf_code text,
  esi_code text,
  gstin text,
  remarks text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

create table if not exists public.client_units (
  id text primary key,
  vendor_id text not null references public.vendors(id),
  client_name text not null,
  unit_name text not null,
  location text not null,
  employee_count integer not null default 0 check (employee_count >= 0),
  remarks text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

create table if not exists public.employees (
  id text primary key,
  vendor_id text not null references public.vendors(id),
  client_unit_id text not null references public.client_units(id),
  employee_code text not null unique,
  name text not null,
  department text not null,
  date_of_joining text not null,
  uan_masked text,
  esi_masked text,
  bank_account_masked text,
  ifsc_masked text,
  bank_name text,
  accommodation_type text not null default 'Tamil Own'
    check (accommodation_type in ('Joy Room', 'Outside Room', 'Tamil Own')),
  room_number text,
  payment_mode text not null default 'bank' check (payment_mode in ('bank', 'cash')),
  salary_amount double precision not null default 0 check (salary_amount >= 0),
  salary_basis text not null default 'monthly' check (salary_basis in ('monthly', 'daily')),
  default_shift text not null default 'General',
  remarks text,
  compliance_status text not null default 'ready',
  status text not null default 'active' check (status in ('active', 'inactive'))
);

create table if not exists public.shift_definitions (
  id text primary key,
  vendor_id text not null references public.vendors(id),
  name text not null,
  start_time text not null,
  end_time text not null,
  remarks text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

create unique index if not exists shift_client_name_unique
  on public.shift_definitions(vendor_id, name);

create table if not exists public.payroll_remarks (
  id text primary key,
  vendor_id text not null references public.vendors(id),
  title text not null,
  category text not null default 'general',
  notes text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

create table if not exists public.payroll_rules (
  id text primary key,
  vendor_id text not null unique references public.vendors(id),
  standard_working_days integer not null default 26 check (standard_working_days between 1 and 31),
  pf_rate double precision not null default 0 check (pf_rate between 0 and 100),
  esi_rate double precision not null default 0 check (esi_rate between 0 and 100),
  professional_tax double precision not null default 0,
  lwf double precision not null default 0,
  overtime_hourly_rate double precision not null default 0,
  paid_leave integer not null default 0 check (paid_leave in (0, 1)),
  paid_week_off integer not null default 0 check (paid_week_off in (0, 1)),
  effective_from text not null default '2026-01-01',
  updated_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

create table if not exists public.attendance_entries (
  id integer generated by default as identity primary key,
  employee_id text not null references public.employees(id),
  attendance_date text not null,
  status_code text not null check (status_code in ('P', 'A', 'L', 'WO', 'H', 'HP')),
  shift_code text not null,
  overtime_hours double precision not null default 0 check (overtime_hours between 0 and 24),
  remarks text,
  source text not null default 'manual',
  updated_by text,
  updated_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  constraint attendance_employee_date_unique unique (employee_id, attendance_date)
);

create table if not exists public.payroll_runs (
  id text primary key,
  vendor_id text not null references public.vendors(id),
  client_unit_id text not null references public.client_units(id),
  pay_period text not null,
  status text not null default 'draft',
  employee_count integer not null default 0,
  gross_earnings double precision not null default 0,
  statutory_deductions double precision not null default 0,
  other_deductions double precision not null default 0,
  accommodation_deductions double precision not null default 0,
  net_payable double precision not null default 0,
  bank_payable double precision not null default 0,
  cash_payable double precision not null default 0,
  issue_count integer not null default 0,
  approved_by text,
  approved_at text,
  updated_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  constraint payroll_unit_period_unique unique (client_unit_id, pay_period)
);

create table if not exists public.payroll_items (
  id text primary key,
  run_id text not null references public.payroll_runs(id),
  employee_id text not null references public.employees(id),
  present_days double precision not null default 0,
  absent_days double precision not null default 0,
  leave_days double precision not null default 0,
  week_off_days double precision not null default 0,
  holiday_present_days double precision not null default 0,
  payable_days double precision not null default 0,
  overtime_hours double precision not null default 0,
  basic double precision not null default 0,
  da double precision not null default 0,
  hra double precision not null default 0,
  conveyance double precision not null default 0,
  food_allowance double precision not null default 0,
  night_allowance double precision not null default 0,
  overtime_wages double precision not null default 0,
  attendance_bonus double precision not null default 0,
  arrears double precision not null default 0,
  holiday_wages double precision not null default 0,
  production_incentive double precision not null default 0,
  medical_allowance double precision not null default 0,
  pf_deduction double precision not null default 0,
  esi_deduction double precision not null default 0,
  professional_tax double precision not null default 0,
  lwf double precision not null default 0,
  canteen double precision not null default 0,
  snacks double precision not null default 0,
  tent double precision not null default 0,
  advance double precision not null default 0,
  other_deduction double precision not null default 0,
  tds double precision not null default 0,
  medical_insurance double precision not null default 0,
  accommodation_deduction double precision not null default 0,
  return_amount double precision not null default 0,
  gross_earnings double precision not null default 0,
  total_deductions double precision not null default 0,
  net_payable double precision not null default 0,
  validation_status text not null default 'ready',
  validation_message text,
  constraint payroll_run_employee_unique unique (run_id, employee_id)
);

create table if not exists public.accommodation_charges (
  id integer generated by default as identity primary key,
  run_id text not null references public.payroll_runs(id),
  employee_id text not null references public.employees(id),
  room_number text,
  id_card double precision not null default 0,
  rent double precision not null default 0,
  bus double precision not null default 0,
  medical double precision not null default 0,
  ticket double precision not null default 0,
  shoe double precision not null default 0,
  advance double precision not null default 0,
  food double precision not null default 0,
  aadhaar_update double precision not null default 0,
  bank_account_charge double precision not null default 0,
  tshirt double precision not null default 0,
  old_pending double precision not null default 0,
  ration_share double precision not null default 0,
  return_amount double precision not null default 0,
  constraint accommodation_run_employee_unique unique (run_id, employee_id)
);

create table if not exists public.audit_events (
  id integer generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  summary text not null,
  actor_email text,
  created_at text not null default (to_char(timezone('UTC', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

create index if not exists client_units_vendor_idx on public.client_units(vendor_id);
create index if not exists employees_vendor_idx on public.employees(vendor_id);
create index if not exists employees_unit_idx on public.employees(client_unit_id);
create index if not exists attendance_date_idx on public.attendance_entries(attendance_date);
create index if not exists attendance_employee_idx on public.attendance_entries(employee_id);
create index if not exists payroll_runs_vendor_idx on public.payroll_runs(vendor_id);
create index if not exists payroll_items_run_idx on public.payroll_items(run_id);
create index if not exists payroll_items_employee_idx on public.payroll_items(employee_id);
create index if not exists accommodation_run_idx on public.accommodation_charges(run_id);
create index if not exists audit_created_idx on public.audit_events(created_at desc);

alter table public.app_users enable row level security;
alter table public.vendors enable row level security;
alter table public.client_units enable row level security;
alter table public.employees enable row level security;
alter table public.shift_definitions enable row level security;
alter table public.payroll_remarks enable row level security;
alter table public.payroll_rules enable row level security;
alter table public.attendance_entries enable row level security;
alter table public.payroll_runs enable row level security;
alter table public.payroll_items enable row level security;
alter table public.accommodation_charges enable row level security;
alter table public.audit_events enable row level security;

-- Browser users never receive direct access to confidential payroll tables.
-- The Edge Function verifies their Supabase Auth JWT, loads their Joy profile,
-- applies module-level permissions, and queries Postgres server-side.
revoke all on public.app_users, public.vendors, public.client_units,
  public.employees, public.shift_definitions, public.payroll_remarks,
  public.payroll_rules, public.attendance_entries, public.payroll_runs,
  public.payroll_items, public.accommodation_charges, public.audit_events
  from anon, authenticated;

insert into public.app_users (
  id, email, full_name, role, status, permissions_json,
  can_approve_payroll, created_by
) values (
  'USER-JOY-PRIMARY-SUPER-ADMIN',
  'praveen.red.07@gmail.com',
  'Praveen',
  'super_admin',
  'active',
  '{"dashboard":"manage","payroll":"manage","attendance":"manage","employees":"manage","accommodation":"manage","payments":"manage","clients":"manage","masters":"manage","settings":"manage","users":"manage"}',
  1,
  'initial-setup'
) on conflict (email) do nothing;

comment on table public.vendors is
  'Payroll entities shown as Clients in the Joy Payroll user interface.';
comment on table public.app_users is
  'Application permission profiles; passwords and verified identities are managed only by Supabase Auth.';

commit;
